package operator

import (
	"context"
	"fmt"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/client-go/util/retry"

	apierrors "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/controller/controllerutil"
	"sigs.k8s.io/controller-runtime/pkg/log"

	podtracev1alpha1 "github.com/podtrace/podtrace/api/v1alpha1"
)

// LabelApplication marks a PodTrace as generated by, and owned by, an
// ApplicationTrace of this name.
const LabelApplication = "podtrace.io/application"

// ApplicationTraceReconciler materializes an ApplicationTrace into a single
// owned PodTrace whose spec.appSelector is the union of the application's
// selectors.
type ApplicationTraceReconciler struct {
	client.Client
	Scheme *runtime.Scheme
}

// +kubebuilder:rbac:groups=podtrace.io,resources=applicationtraces,verbs=get;list;watch;update;patch;delete
// +kubebuilder:rbac:groups=podtrace.io,resources=applicationtraces/status,verbs=get;update;patch
// +kubebuilder:rbac:groups=podtrace.io,resources=applicationtraces/finalizers,verbs=update
// +kubebuilder:rbac:groups=podtrace.io,resources=podtraces,verbs=get;list;watch;create;update;patch;delete

func (r *ApplicationTraceReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	logger := log.FromContext(ctx).WithValues("applicationtrace", req.String())

	var app podtracev1alpha1.ApplicationTrace
	if err := r.Get(ctx, req.NamespacedName, &app); err != nil {
		if apierrors.IsNotFound(err) {
			return ctrl.Result{}, nil
		}
		return ctrl.Result{}, fmt.Errorf("get ApplicationTrace: %w", err)
	}

	if app.Spec.Paused {
		r.setCondition(&app, ConditionPaused, metav1.ConditionTrue, "Paused", "spec.paused is true")
	} else {
		r.setCondition(&app, ConditionPaused, metav1.ConditionFalse, "NotPaused", "")
	}

	pt, err := r.ensureChildPodTrace(ctx, &app)
	if err != nil {
		r.setCondition(&app, ConditionDegraded, metav1.ConditionTrue, "ChildPodTrace", err.Error())
		r.setCondition(&app, ConditionReady, metav1.ConditionFalse, "ChildPodTrace", err.Error())
		if perr := r.patchStatus(ctx, &app); perr != nil {
			return ctrl.Result{}, perr
		}
		return ctrl.Result{}, err
	}
	r.setCondition(&app, ConditionDegraded, metav1.ConditionFalse, "Reconciled", "")

	r.aggregateStatus(&app, pt)
	r.setCondition(&app, ConditionReconciled, metav1.ConditionTrue, "Reconciled",
		fmt.Sprintf("PodTrace %q in sync", pt.Name))

	if err := r.patchStatus(ctx, &app); err != nil {
		return ctrl.Result{}, err
	}
	logger.V(1).Info("reconciled", "podtrace", pt.Name, "matchedPods", app.Status.MatchedPods)
	return ctrl.Result{}, nil
}

// ensureChildPodTrace create-or-updates the single owned PodTrace, named after
// the ApplicationTrace, translating the app's selectors into spec.appSelector.
func (r *ApplicationTraceReconciler) ensureChildPodTrace(ctx context.Context, app *podtracev1alpha1.ApplicationTrace) (*podtracev1alpha1.PodTrace, error) {
	pt := &podtracev1alpha1.PodTrace{
		ObjectMeta: metav1.ObjectMeta{
			Name:      app.Name,
			Namespace: app.Namespace,
		},
	}
	// Refuse to adopt a pre-existing PodTrace this controller did not
	// create: CreateOrUpdate would silently overwrite a user-authored spec
	// and add an ownerReference that garbage-collects the user's resource
	// when the ApplicationTrace is deleted.
	var existing podtracev1alpha1.PodTrace
	err := r.Get(ctx, types.NamespacedName{Namespace: app.Namespace, Name: app.Name}, &existing)
	switch {
	case err == nil:
		owner := metav1.GetControllerOf(&existing)
		if owner == nil || owner.Kind != "ApplicationTrace" || owner.UID != app.UID {
			return nil, fmt.Errorf(
				"PodTrace %s/%s already exists and is not managed by this ApplicationTrace; rename the ApplicationTrace or delete the existing PodTrace",
				app.Namespace, app.Name)
		}
	case !apierrors.IsNotFound(err):
		return nil, fmt.Errorf("get PodTrace %s/%s: %w", app.Namespace, app.Name, err)
	}
	_, err = controllerutil.CreateOrUpdate(ctx, r.Client, pt, func() error {
		pt.Labels = mergeLabels(pt.Labels, map[string]string{
			LabelManagedBy:   ManagedByValue,
			LabelApplication: app.Name,
		})
		spec := app.Spec.DeepCopy()
		pt.Spec = podtracev1alpha1.PodTraceSpec{
			AppSelector:       &podtracev1alpha1.AppSelector{MatchSelectors: spec.Selectors},
			NamespaceSelector: spec.NamespaceSelector,
			ExporterRef:       spec.ExporterRef,
			Filters:           spec.Filters,
			SamplePercent:     spec.SamplePercent,
			Thresholds:        spec.Thresholds,
			Paused:            spec.Paused,
		}
		return controllerutil.SetControllerReference(app, pt, r.Scheme)
	})
	if err != nil {
		return nil, fmt.Errorf("ensure PodTrace %s/%s: %w", app.Namespace, app.Name, err)
	}
	return pt, nil
}

// aggregateStatus folds the generated PodTrace's observed state up onto the
// ApplicationTrace, and mirrors the child's Ready condition.
func (r *ApplicationTraceReconciler) aggregateStatus(app *podtracev1alpha1.ApplicationTrace, pt *podtracev1alpha1.PodTrace) {
	app.Status.PodTraceRef = pt.Name
	app.Status.MatchedPods = pt.Status.MatchedPods
	app.Status.TargetNamespaces = pt.Status.TargetNamespaces
	app.Status.ObservedGeneration = app.Generation

	status := metav1.ConditionFalse
	reason, message := "ChildNotReady", "generated PodTrace has not reported readiness yet"
	for i := range pt.Status.Conditions {
		c := pt.Status.Conditions[i]
		if c.Type == ConditionReady {
			status = c.Status
			reason = c.Reason
			message = c.Message
			break
		}
	}
	r.setCondition(app, ConditionReady, status, reason, message)
}

func (r *ApplicationTraceReconciler) setCondition(app *podtracev1alpha1.ApplicationTrace, condType string, status metav1.ConditionStatus, reason, message string) {
	app.Status.Conditions = upsertCondition(app.Status.Conditions, metav1.Condition{
		Type:               condType,
		Status:             status,
		Reason:             reason,
		Message:            message,
		LastTransitionTime: metav1.Now(),
		ObservedGeneration: app.Generation,
	})
}

// patchStatus writes the computed status, retrying on optimistic-concurrency
// conflicts by re-reading the latest object and re-applying the computed
// status. Conflicts used to be swallowed with no requeue, silently dropping
// the entire computed status until some unrelated event arrived.
func (r *ApplicationTraceReconciler) patchStatus(ctx context.Context, app *podtracev1alpha1.ApplicationTrace) error {
	desired := app.Status.DeepCopy()
	key := types.NamespacedName{Namespace: app.Namespace, Name: app.Name}
	err := retry.RetryOnConflict(retry.DefaultRetry, func() error {
		var latest podtracev1alpha1.ApplicationTrace
		if err := r.Get(ctx, key, &latest); err != nil {
			return err
		}
		latest.Status = *desired.DeepCopy()
		return r.Status().Update(ctx, &latest)
	})
	if err != nil {
		if apierrors.IsNotFound(err) {
			return nil
		}
		return fmt.Errorf("update status: %w", err)
	}
	return nil
}

func (r *ApplicationTraceReconciler) SetupWithManager(mgr ctrl.Manager) error {
	return ctrl.NewControllerManagedBy(mgr).
		Named("applicationtrace").
		For(&podtracev1alpha1.ApplicationTrace{}).
		Owns(&podtracev1alpha1.PodTrace{}).
		WithOptions(defaultControllerOptions()).
		Complete(r)
}
