/*
Copyright 2026 Ghassan Malke.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// AgentMetricsLabelsSpecApplyConfiguration represents a declarative configuration of the AgentMetricsLabelsSpec type for use
// with apply.
//
// AgentMetricsLabelsSpec opts into labels that are deliberately absent by
// default because each one multiplies series count.
type AgentMetricsLabelsSpecApplyConfiguration struct {
	Pod     *bool `json:"pod,omitempty"`
	Process *bool `json:"process,omitempty"`
}

// AgentMetricsLabelsSpecApplyConfiguration constructs a declarative configuration of the AgentMetricsLabelsSpec type for use with
// apply.
func AgentMetricsLabelsSpec() *AgentMetricsLabelsSpecApplyConfiguration {
	return &AgentMetricsLabelsSpecApplyConfiguration{}
}

// WithPod sets the Pod field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Pod field is set to the value of the last call.
func (b *AgentMetricsLabelsSpecApplyConfiguration) WithPod(value bool) *AgentMetricsLabelsSpecApplyConfiguration {
	b.Pod = &value
	return b
}

// WithProcess sets the Process field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Process field is set to the value of the last call.
func (b *AgentMetricsLabelsSpecApplyConfiguration) WithProcess(value bool) *AgentMetricsLabelsSpecApplyConfiguration {
	b.Process = &value
	return b
}
