/*
Copyright 2026 Ghassan Malke.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// AgentSpecApplyConfiguration represents a declarative configuration of the AgentSpec type for use
// with apply.
//
// AgentSpec tunes the per-node tracer DaemonSet.
type AgentSpecApplyConfiguration struct {
	Resources            *v1.ResourceRequirements             `json:"resources,omitempty"`
	PriorityClassName    *string                              `json:"priorityClassName,omitempty"`
	LogLevel             *string                              `json:"logLevel,omitempty"`
	EventBufferSize      *int32                               `json:"eventBufferSize,omitempty"`
	StatusReportInterval *metav1.Duration                     `json:"statusReportInterval,omitempty"`
	DNSPacketCapture     *bool                                `json:"dnsPacketCapture,omitempty"`
	Alerting             *AgentAlertingSpecApplyConfiguration `json:"alerting,omitempty"`
}

// AgentSpecApplyConfiguration constructs a declarative configuration of the AgentSpec type for use with
// apply.
func AgentSpec() *AgentSpecApplyConfiguration {
	return &AgentSpecApplyConfiguration{}
}

// WithResources sets the Resources field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resources field is set to the value of the last call.
func (b *AgentSpecApplyConfiguration) WithResources(value v1.ResourceRequirements) *AgentSpecApplyConfiguration {
	b.Resources = &value
	return b
}

// WithPriorityClassName sets the PriorityClassName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PriorityClassName field is set to the value of the last call.
func (b *AgentSpecApplyConfiguration) WithPriorityClassName(value string) *AgentSpecApplyConfiguration {
	b.PriorityClassName = &value
	return b
}

// WithLogLevel sets the LogLevel field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LogLevel field is set to the value of the last call.
func (b *AgentSpecApplyConfiguration) WithLogLevel(value string) *AgentSpecApplyConfiguration {
	b.LogLevel = &value
	return b
}

// WithEventBufferSize sets the EventBufferSize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EventBufferSize field is set to the value of the last call.
func (b *AgentSpecApplyConfiguration) WithEventBufferSize(value int32) *AgentSpecApplyConfiguration {
	b.EventBufferSize = &value
	return b
}

// WithStatusReportInterval sets the StatusReportInterval field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StatusReportInterval field is set to the value of the last call.
func (b *AgentSpecApplyConfiguration) WithStatusReportInterval(value metav1.Duration) *AgentSpecApplyConfiguration {
	b.StatusReportInterval = &value
	return b
}

// WithDNSPacketCapture sets the DNSPacketCapture field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DNSPacketCapture field is set to the value of the last call.
func (b *AgentSpecApplyConfiguration) WithDNSPacketCapture(value bool) *AgentSpecApplyConfiguration {
	b.DNSPacketCapture = &value
	return b
}

// WithAlerting sets the Alerting field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Alerting field is set to the value of the last call.
func (b *AgentSpecApplyConfiguration) WithAlerting(value *AgentAlertingSpecApplyConfiguration) *AgentSpecApplyConfiguration {
	b.Alerting = value
	return b
}
