/*
Copyright 2026 Ghassan Malke.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// AgentMetricsSpecApplyConfiguration represents a declarative configuration of the AgentMetricsSpec type for use
// with apply.
//
// AgentMetricsSpec configures the continuous metrics plane.
type AgentMetricsSpecApplyConfiguration struct {
	Enabled              *bool                                     `json:"enabled,omitempty"`
	ExcludeNamespaces    []string                                  `json:"excludeNamespaces,omitempty"`
	Labels               *AgentMetricsLabelsSpecApplyConfiguration `json:"labels,omitempty"`
	SeriesBudget         *int32                                    `json:"seriesBudget,omitempty"`
	NativeHistograms     *bool                                     `json:"nativeHistograms,omitempty"`
	SemanticConventions  *bool                                     `json:"semanticConventions,omitempty"`
	AttributeCardinality *int32                                    `json:"attributeCardinality,omitempty"`
}

// AgentMetricsSpecApplyConfiguration constructs a declarative configuration of the AgentMetricsSpec type for use with
// apply.
func AgentMetricsSpec() *AgentMetricsSpecApplyConfiguration {
	return &AgentMetricsSpecApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *AgentMetricsSpecApplyConfiguration) WithEnabled(value bool) *AgentMetricsSpecApplyConfiguration {
	b.Enabled = &value
	return b
}

// WithExcludeNamespaces adds the given value to the ExcludeNamespaces field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ExcludeNamespaces field.
func (b *AgentMetricsSpecApplyConfiguration) WithExcludeNamespaces(values ...string) *AgentMetricsSpecApplyConfiguration {
	for i := range values {
		b.ExcludeNamespaces = append(b.ExcludeNamespaces, values[i])
	}
	return b
}

// WithLabels sets the Labels field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Labels field is set to the value of the last call.
func (b *AgentMetricsSpecApplyConfiguration) WithLabels(value *AgentMetricsLabelsSpecApplyConfiguration) *AgentMetricsSpecApplyConfiguration {
	b.Labels = value
	return b
}

// WithSeriesBudget sets the SeriesBudget field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SeriesBudget field is set to the value of the last call.
func (b *AgentMetricsSpecApplyConfiguration) WithSeriesBudget(value int32) *AgentMetricsSpecApplyConfiguration {
	b.SeriesBudget = &value
	return b
}

// WithNativeHistograms sets the NativeHistograms field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NativeHistograms field is set to the value of the last call.
func (b *AgentMetricsSpecApplyConfiguration) WithNativeHistograms(value bool) *AgentMetricsSpecApplyConfiguration {
	b.NativeHistograms = &value
	return b
}

// WithSemanticConventions sets the SemanticConventions field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SemanticConventions field is set to the value of the last call.
func (b *AgentMetricsSpecApplyConfiguration) WithSemanticConventions(value bool) *AgentMetricsSpecApplyConfiguration {
	b.SemanticConventions = &value
	return b
}

// WithAttributeCardinality sets the AttributeCardinality field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AttributeCardinality field is set to the value of the last call.
func (b *AgentMetricsSpecApplyConfiguration) WithAttributeCardinality(value int32) *AgentMetricsSpecApplyConfiguration {
	b.AttributeCardinality = &value
	return b
}
