/*
Copyright 2026 Ghassan Malke.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// AgentInspectionThresholdsSpecApplyConfiguration represents a declarative configuration of the AgentInspectionThresholdsSpec type for use
// with apply.
//
// AgentInspectionThresholdsSpec tunes the built-in rules. Rule shapes are not
// configurable — that is what keeps the issue vocabulary meaningful — but the
// numbers they compare against are workload-specific.
type AgentInspectionThresholdsSpecApplyConfiguration struct {
	// ErrorRatePercent is the application-layer error ratio above which
	// l7.error_rate fires.
	ErrorRatePercent *int32 `json:"errorRatePercent,omitempty"`
	// MinRequestsPerMinute is the traffic floor below which the error-rate
	// rule stays quiet, so one failed request in an idle interval does not
	// read as a 100% error rate. Expressed per minute rather than per second
	// because the useful values are fractions of a request per second.
	MinRequestsPerMinute *int32 `json:"minRequestsPerMinute,omitempty"`
	// MeanLatency is the mean request duration above which
	// l7.latency_degraded fires.
	MeanLatency *v1.Duration `json:"meanLatency,omitempty"`
	// AcquireMean is the mean time callers spend queued for a free database
	// connection above which db.connection_acquire_slow fires. Go database/sql only.
	AcquireMean *v1.Duration `json:"acquireMean,omitempty"`
}

// AgentInspectionThresholdsSpecApplyConfiguration constructs a declarative configuration of the AgentInspectionThresholdsSpec type for use with
// apply.
func AgentInspectionThresholdsSpec() *AgentInspectionThresholdsSpecApplyConfiguration {
	return &AgentInspectionThresholdsSpecApplyConfiguration{}
}

// WithErrorRatePercent sets the ErrorRatePercent field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ErrorRatePercent field is set to the value of the last call.
func (b *AgentInspectionThresholdsSpecApplyConfiguration) WithErrorRatePercent(value int32) *AgentInspectionThresholdsSpecApplyConfiguration {
	b.ErrorRatePercent = &value
	return b
}

// WithMinRequestsPerMinute sets the MinRequestsPerMinute field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinRequestsPerMinute field is set to the value of the last call.
func (b *AgentInspectionThresholdsSpecApplyConfiguration) WithMinRequestsPerMinute(value int32) *AgentInspectionThresholdsSpecApplyConfiguration {
	b.MinRequestsPerMinute = &value
	return b
}

// WithMeanLatency sets the MeanLatency field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MeanLatency field is set to the value of the last call.
func (b *AgentInspectionThresholdsSpecApplyConfiguration) WithMeanLatency(value v1.Duration) *AgentInspectionThresholdsSpecApplyConfiguration {
	b.MeanLatency = &value
	return b
}

// WithAcquireMean sets the AcquireMean field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AcquireMean field is set to the value of the last call.
func (b *AgentInspectionThresholdsSpecApplyConfiguration) WithAcquireMean(value v1.Duration) *AgentInspectionThresholdsSpecApplyConfiguration {
	b.AcquireMean = &value
	return b
}
