/*
Copyright 2026 Ghassan Malke.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// AgentInspectionsSpecApplyConfiguration represents a declarative configuration of the AgentInspectionsSpec type for use
// with apply.
//
// AgentInspectionsSpec configures continuous inspections: the half of the
// plane that decides something is wrong, rather than only recording it.
type AgentInspectionsSpecApplyConfiguration struct {
	// Enabled runs the inspections. On unless set to false; they read the
	// metrics plane, so they are also off whenever it is.
	Enabled *bool `json:"enabled,omitempty"`
	// Interval is how often rules are evaluated. It doubles as the rate
	// window, so it has to be long enough for a counter delta to mean
	// something and short enough for an issue to be noticed.
	Interval *v1.Duration `json:"interval,omitempty"`
	// Alerts controls whether an activated issue is raised as an alert,
	// which is what lets a PodTraceSchedule with an Issue trigger start a
	// session from it. With this off, inspections only expose
	// podtrace_issue_active.
	Alerts *bool `json:"alerts,omitempty"`
	// Budget bounds how many distinct issue instances an agent tracks.
	Budget *int32 `json:"budget,omitempty"`
	// HoldTime replaces every rule's own hold duration, the time a condition
	// must hold before its issue activates. Leave unset to keep the built-in
	// per-rule defaults, which suit their signals; set it shorter for a test
	// run or longer for a workload whose bursts are expected.
	HoldTime *v1.Duration `json:"holdTime,omitempty"`
	// Thresholds tune when the built-in rules fire.
	Thresholds *AgentInspectionThresholdsSpecApplyConfiguration `json:"thresholds,omitempty"`
}

// AgentInspectionsSpecApplyConfiguration constructs a declarative configuration of the AgentInspectionsSpec type for use with
// apply.
func AgentInspectionsSpec() *AgentInspectionsSpecApplyConfiguration {
	return &AgentInspectionsSpecApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *AgentInspectionsSpecApplyConfiguration) WithEnabled(value bool) *AgentInspectionsSpecApplyConfiguration {
	b.Enabled = &value
	return b
}

// WithInterval sets the Interval field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Interval field is set to the value of the last call.
func (b *AgentInspectionsSpecApplyConfiguration) WithInterval(value v1.Duration) *AgentInspectionsSpecApplyConfiguration {
	b.Interval = &value
	return b
}

// WithAlerts sets the Alerts field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Alerts field is set to the value of the last call.
func (b *AgentInspectionsSpecApplyConfiguration) WithAlerts(value bool) *AgentInspectionsSpecApplyConfiguration {
	b.Alerts = &value
	return b
}

// WithBudget sets the Budget field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Budget field is set to the value of the last call.
func (b *AgentInspectionsSpecApplyConfiguration) WithBudget(value int32) *AgentInspectionsSpecApplyConfiguration {
	b.Budget = &value
	return b
}

// WithHoldTime sets the HoldTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HoldTime field is set to the value of the last call.
func (b *AgentInspectionsSpecApplyConfiguration) WithHoldTime(value v1.Duration) *AgentInspectionsSpecApplyConfiguration {
	b.HoldTime = &value
	return b
}

// WithThresholds sets the Thresholds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Thresholds field is set to the value of the last call.
func (b *AgentInspectionsSpecApplyConfiguration) WithThresholds(value *AgentInspectionThresholdsSpecApplyConfiguration) *AgentInspectionsSpecApplyConfiguration {
	b.Thresholds = value
	return b
}
