/*
Copyright 2026 Ghassan Malke.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// AgentAlertingSpecApplyConfiguration represents a declarative configuration of the AgentAlertingSpec type for use
// with apply.
//
// AgentAlertingSpec configures agent-side resource-limit alert delivery.
type AgentAlertingSpecApplyConfiguration struct {
	Enabled              *bool   `json:"enabled,omitempty"`
	WebhookURL           *string `json:"webhookURL,omitempty"`
	AllowInsecureWebhook *bool   `json:"allowInsecureWebhook,omitempty"`
}

// AgentAlertingSpecApplyConfiguration constructs a declarative configuration of the AgentAlertingSpec type for use with
// apply.
func AgentAlertingSpec() *AgentAlertingSpecApplyConfiguration {
	return &AgentAlertingSpecApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *AgentAlertingSpecApplyConfiguration) WithEnabled(value bool) *AgentAlertingSpecApplyConfiguration {
	b.Enabled = &value
	return b
}

// WithWebhookURL sets the WebhookURL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WebhookURL field is set to the value of the last call.
func (b *AgentAlertingSpecApplyConfiguration) WithWebhookURL(value string) *AgentAlertingSpecApplyConfiguration {
	b.WebhookURL = &value
	return b
}

// WithAllowInsecureWebhook sets the AllowInsecureWebhook field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AllowInsecureWebhook field is set to the value of the last call.
func (b *AgentAlertingSpecApplyConfiguration) WithAllowInsecureWebhook(value bool) *AgentAlertingSpecApplyConfiguration {
	b.AllowInsecureWebhook = &value
	return b
}
