/*
Copyright 2026 Ghassan Malke.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/podtrace/podtrace/api/v1alpha1"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ApplicationTraceSpecApplyConfiguration represents a declarative configuration of the ApplicationTraceSpec type for use
// with apply.
//
// ApplicationTraceSpec declares continuous tracing for a whole application,
// a set of workloads (selectors), optionally across namespaces.
type ApplicationTraceSpecApplyConfiguration struct {
	Selectors         []v1.LabelSelectorApplyConfiguration    `json:"selectors,omitempty"`
	NamespaceSelector *v1.LabelSelectorApplyConfiguration     `json:"namespaceSelector,omitempty"`
	ExporterRef       *LocalObjectReferenceApplyConfiguration `json:"exporterRef,omitempty"`
	Filters           []apiv1alpha1.EventFilter               `json:"filters,omitempty"`
	SamplePercent     *int32                                  `json:"samplePercent,omitempty"`
	Thresholds        *ThresholdsApplyConfiguration           `json:"thresholds,omitempty"`
	Paused            *bool                                   `json:"paused,omitempty"`
}

// ApplicationTraceSpecApplyConfiguration constructs a declarative configuration of the ApplicationTraceSpec type for use with
// apply.
func ApplicationTraceSpec() *ApplicationTraceSpecApplyConfiguration {
	return &ApplicationTraceSpecApplyConfiguration{}
}

// WithSelectors adds the given value to the Selectors field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Selectors field.
func (b *ApplicationTraceSpecApplyConfiguration) WithSelectors(values ...*v1.LabelSelectorApplyConfiguration) *ApplicationTraceSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithSelectors")
		}
		b.Selectors = append(b.Selectors, *values[i])
	}
	return b
}

// WithNamespaceSelector sets the NamespaceSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NamespaceSelector field is set to the value of the last call.
func (b *ApplicationTraceSpecApplyConfiguration) WithNamespaceSelector(value *v1.LabelSelectorApplyConfiguration) *ApplicationTraceSpecApplyConfiguration {
	b.NamespaceSelector = value
	return b
}

// WithExporterRef sets the ExporterRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExporterRef field is set to the value of the last call.
func (b *ApplicationTraceSpecApplyConfiguration) WithExporterRef(value *LocalObjectReferenceApplyConfiguration) *ApplicationTraceSpecApplyConfiguration {
	b.ExporterRef = value
	return b
}

// WithFilters adds the given value to the Filters field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Filters field.
func (b *ApplicationTraceSpecApplyConfiguration) WithFilters(values ...apiv1alpha1.EventFilter) *ApplicationTraceSpecApplyConfiguration {
	for i := range values {
		b.Filters = append(b.Filters, values[i])
	}
	return b
}

// WithSamplePercent sets the SamplePercent field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SamplePercent field is set to the value of the last call.
func (b *ApplicationTraceSpecApplyConfiguration) WithSamplePercent(value int32) *ApplicationTraceSpecApplyConfiguration {
	b.SamplePercent = &value
	return b
}

// WithThresholds sets the Thresholds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Thresholds field is set to the value of the last call.
func (b *ApplicationTraceSpecApplyConfiguration) WithThresholds(value *ThresholdsApplyConfiguration) *ApplicationTraceSpecApplyConfiguration {
	b.Thresholds = value
	return b
}

// WithPaused sets the Paused field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Paused field is set to the value of the last call.
func (b *ApplicationTraceSpecApplyConfiguration) WithPaused(value bool) *ApplicationTraceSpecApplyConfiguration {
	b.Paused = &value
	return b
}
