/*
Copyright 2026 Ghassan Malke.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ApplicationTraceStatusApplyConfiguration represents a declarative configuration of the ApplicationTraceStatus type for use
// with apply.
//
// ApplicationTraceStatus reflects the observed state of an ApplicationTrace,
// aggregated from its generated PodTrace.
type ApplicationTraceStatusApplyConfiguration struct {
	PodTraceRef        *string                          `json:"podTraceRef,omitempty"`
	MatchedPods        *int32                           `json:"matchedPods,omitempty"`
	TargetNamespaces   []string                         `json:"targetNamespaces,omitempty"`
	Conditions         []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	ObservedGeneration *int64                           `json:"observedGeneration,omitempty"`
}

// ApplicationTraceStatusApplyConfiguration constructs a declarative configuration of the ApplicationTraceStatus type for use with
// apply.
func ApplicationTraceStatus() *ApplicationTraceStatusApplyConfiguration {
	return &ApplicationTraceStatusApplyConfiguration{}
}

// WithPodTraceRef sets the PodTraceRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodTraceRef field is set to the value of the last call.
func (b *ApplicationTraceStatusApplyConfiguration) WithPodTraceRef(value string) *ApplicationTraceStatusApplyConfiguration {
	b.PodTraceRef = &value
	return b
}

// WithMatchedPods sets the MatchedPods field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MatchedPods field is set to the value of the last call.
func (b *ApplicationTraceStatusApplyConfiguration) WithMatchedPods(value int32) *ApplicationTraceStatusApplyConfiguration {
	b.MatchedPods = &value
	return b
}

// WithTargetNamespaces adds the given value to the TargetNamespaces field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the TargetNamespaces field.
func (b *ApplicationTraceStatusApplyConfiguration) WithTargetNamespaces(values ...string) *ApplicationTraceStatusApplyConfiguration {
	for i := range values {
		b.TargetNamespaces = append(b.TargetNamespaces, values[i])
	}
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *ApplicationTraceStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *ApplicationTraceStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *ApplicationTraceStatusApplyConfiguration) WithObservedGeneration(value int64) *ApplicationTraceStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}
