/*
Copyright 2026 Ghassan Malke.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// AppSelectorApplyConfiguration represents a declarative configuration of the AppSelector type for use
// with apply.
//
// AppSelector matches pods that satisfy ANY of its label selectors, so
// an application composed of several workloads with distinct labels
// can be traced as one.
type AppSelectorApplyConfiguration struct {
	MatchSelectors []v1.LabelSelectorApplyConfiguration `json:"matchSelectors,omitempty"`
}

// AppSelectorApplyConfiguration constructs a declarative configuration of the AppSelector type for use with
// apply.
func AppSelector() *AppSelectorApplyConfiguration {
	return &AppSelectorApplyConfiguration{}
}

// WithMatchSelectors adds the given value to the MatchSelectors field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the MatchSelectors field.
func (b *AppSelectorApplyConfiguration) WithMatchSelectors(values ...*v1.LabelSelectorApplyConfiguration) *AppSelectorApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithMatchSelectors")
		}
		b.MatchSelectors = append(b.MatchSelectors, *values[i])
	}
	return b
}
