/*
Copyright 2026 Ghassan Malke.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// BTFConfigMapSourceApplyConfiguration represents a declarative configuration of the BTFConfigMapSource type for use
// with apply.
//
// BTFConfigMapSource names the ConfigMap and key holding a BTF blob.
type BTFConfigMapSourceApplyConfiguration struct {
	Name *string `json:"name,omitempty"`
	// Key defaults to "vmlinux.btf".
	Key *string `json:"key,omitempty"`
}

// BTFConfigMapSourceApplyConfiguration constructs a declarative configuration of the BTFConfigMapSource type for use with
// apply.
func BTFConfigMapSource() *BTFConfigMapSourceApplyConfiguration {
	return &BTFConfigMapSourceApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *BTFConfigMapSourceApplyConfiguration) WithName(value string) *BTFConfigMapSourceApplyConfiguration {
	b.Name = &value
	return b
}

// WithKey sets the Key field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Key field is set to the value of the last call.
func (b *BTFConfigMapSourceApplyConfiguration) WithKey(value string) *BTFConfigMapSourceApplyConfiguration {
	b.Key = &value
	return b
}
