/*
Copyright 2026 Ghassan Malke.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// BTFSourceApplyConfiguration represents a declarative configuration of the BTFSource type for use
// with apply.
//
// BTFSource locates the BTF blob the agent loads when btfMode is "file".
// Exactly one of its fields may be set.
//
// The blob may be a raw BTF file -- what "bpftool gen min_core_btf" and the
// BTFHub archive produce -- or an ELF carrying a .BTF section, such as a
// vmlinux built with CONFIG_DEBUG_INFO_BTF. A minimised blob is tens of
// kilobytes and fits a ConfigMap; a whole vmlinux does not.
type BTFSourceApplyConfiguration struct {
	// ConfigMap names a ConfigMap in the system namespace whose binaryData
	// holds the blob. Preferred: it survives node replacement and needs no
	// access to the node's filesystem. A ConfigMap caps at 1MiB, so the blob
	// must be minimised.
	ConfigMap *BTFConfigMapSourceApplyConfiguration `json:"configMap,omitempty"`
	// HostPath reads the blob from an absolute path present on every node the
	// agent runs on. For a blob too large for a ConfigMap, or one already
	// staged on the node by other tooling.
	HostPath *string `json:"hostPath,omitempty"`
}

// BTFSourceApplyConfiguration constructs a declarative configuration of the BTFSource type for use with
// apply.
func BTFSource() *BTFSourceApplyConfiguration {
	return &BTFSourceApplyConfiguration{}
}

// WithConfigMap sets the ConfigMap field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConfigMap field is set to the value of the last call.
func (b *BTFSourceApplyConfiguration) WithConfigMap(value *BTFConfigMapSourceApplyConfiguration) *BTFSourceApplyConfiguration {
	b.ConfigMap = value
	return b
}

// WithHostPath sets the HostPath field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HostPath field is set to the value of the last call.
func (b *BTFSourceApplyConfiguration) WithHostPath(value string) *BTFSourceApplyConfiguration {
	b.HostPath = &value
	return b
}
