/*
Copyright 2026 Ghassan Malke.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// CaptureSpecApplyConfiguration represents a declarative configuration of the CaptureSpec type for use
// with apply.
//
// CaptureSpec selects additional L7 request/response data to capture.
type CaptureSpecApplyConfiguration struct {
	Headers []string `json:"headers,omitempty"`
}

// CaptureSpecApplyConfiguration constructs a declarative configuration of the CaptureSpec type for use with
// apply.
func CaptureSpec() *CaptureSpecApplyConfiguration {
	return &CaptureSpecApplyConfiguration{}
}

// WithHeaders adds the given value to the Headers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Headers field.
func (b *CaptureSpecApplyConfiguration) WithHeaders(values ...string) *CaptureSpecApplyConfiguration {
	for i := range values {
		b.Headers = append(b.Headers, values[i])
	}
	return b
}
