/*
Copyright 2026 Ghassan Malke.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// DataDogExporterApplyConfiguration represents a declarative configuration of the DataDogExporter type for use
// with apply.
//
// DataDogExporter configures the DataDog exporter.
type DataDogExporterApplyConfiguration struct {
	Endpoint *string `json:"endpoint,omitempty"`
	// Site, e.g. "datadoghq.com" or "datadoghq.eu". Defaults to datadoghq.com.
	// Used as a label for routing and (when Endpoint is empty) to derive
	// a default Endpoint pointing at a conventional DataDog Agent
	// service name.
	Site *string `json:"site,omitempty"`
	// APIKeySecretRef references the DataDog API key in a Secret in the
	// same namespace as the ExporterConfig.
	APIKeySecretRef *SecretKeySelectorApplyConfiguration `json:"apiKeySecretRef,omitempty"`
}

// DataDogExporterApplyConfiguration constructs a declarative configuration of the DataDogExporter type for use with
// apply.
func DataDogExporter() *DataDogExporterApplyConfiguration {
	return &DataDogExporterApplyConfiguration{}
}

// WithEndpoint sets the Endpoint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Endpoint field is set to the value of the last call.
func (b *DataDogExporterApplyConfiguration) WithEndpoint(value string) *DataDogExporterApplyConfiguration {
	b.Endpoint = &value
	return b
}

// WithSite sets the Site field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Site field is set to the value of the last call.
func (b *DataDogExporterApplyConfiguration) WithSite(value string) *DataDogExporterApplyConfiguration {
	b.Site = &value
	return b
}

// WithAPIKeySecretRef sets the APIKeySecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIKeySecretRef field is set to the value of the last call.
func (b *DataDogExporterApplyConfiguration) WithAPIKeySecretRef(value *SecretKeySelectorApplyConfiguration) *DataDogExporterApplyConfiguration {
	b.APIKeySecretRef = value
	return b
}
