/*
Copyright 2026 Ghassan Malke.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/podtrace/podtrace/api/v1alpha1"
)

// ExporterConfigSpecApplyConfiguration represents a declarative configuration of the ExporterConfigSpec type for use
// with apply.
//
// ExporterConfigSpec configures a reusable trace exporter.
// Exactly one of the typed fields (OTLP, Jaeger, Zipkin, Splunk, DataDog)
// must be populated, and it must match the Type field.
type ExporterConfigSpecApplyConfiguration struct {
	// Type selects the exporter implementation.
	Type    *apiv1alpha1.ExporterType          `json:"type,omitempty"`
	OTLP    *OTLPExporterApplyConfiguration    `json:"otlp,omitempty"`
	Jaeger  *JaegerExporterApplyConfiguration  `json:"jaeger,omitempty"`
	Zipkin  *ZipkinExporterApplyConfiguration  `json:"zipkin,omitempty"`
	Splunk  *SplunkExporterApplyConfiguration  `json:"splunk,omitempty"`
	DataDog *DataDogExporterApplyConfiguration `json:"datadog,omitempty"`
	// SamplePercent sets an exporter-level sampling rate cap, 0-100.
	// If both this and the referent trace's SamplePercent are set, the minimum applies.
	SamplePercent *int32 `json:"samplePercent,omitempty"`
}

// ExporterConfigSpecApplyConfiguration constructs a declarative configuration of the ExporterConfigSpec type for use with
// apply.
func ExporterConfigSpec() *ExporterConfigSpecApplyConfiguration {
	return &ExporterConfigSpecApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *ExporterConfigSpecApplyConfiguration) WithType(value apiv1alpha1.ExporterType) *ExporterConfigSpecApplyConfiguration {
	b.Type = &value
	return b
}

// WithOTLP sets the OTLP field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OTLP field is set to the value of the last call.
func (b *ExporterConfigSpecApplyConfiguration) WithOTLP(value *OTLPExporterApplyConfiguration) *ExporterConfigSpecApplyConfiguration {
	b.OTLP = value
	return b
}

// WithJaeger sets the Jaeger field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Jaeger field is set to the value of the last call.
func (b *ExporterConfigSpecApplyConfiguration) WithJaeger(value *JaegerExporterApplyConfiguration) *ExporterConfigSpecApplyConfiguration {
	b.Jaeger = value
	return b
}

// WithZipkin sets the Zipkin field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Zipkin field is set to the value of the last call.
func (b *ExporterConfigSpecApplyConfiguration) WithZipkin(value *ZipkinExporterApplyConfiguration) *ExporterConfigSpecApplyConfiguration {
	b.Zipkin = value
	return b
}

// WithSplunk sets the Splunk field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Splunk field is set to the value of the last call.
func (b *ExporterConfigSpecApplyConfiguration) WithSplunk(value *SplunkExporterApplyConfiguration) *ExporterConfigSpecApplyConfiguration {
	b.Splunk = value
	return b
}

// WithDataDog sets the DataDog field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DataDog field is set to the value of the last call.
func (b *ExporterConfigSpecApplyConfiguration) WithDataDog(value *DataDogExporterApplyConfiguration) *ExporterConfigSpecApplyConfiguration {
	b.DataDog = value
	return b
}

// WithSamplePercent sets the SamplePercent field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SamplePercent field is set to the value of the last call.
func (b *ExporterConfigSpecApplyConfiguration) WithSamplePercent(value int32) *ExporterConfigSpecApplyConfiguration {
	b.SamplePercent = &value
	return b
}
