/*
Copyright 2026 Ghassan Malke.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ExporterConfigStatusApplyConfiguration represents a declarative configuration of the ExporterConfigStatus type for use
// with apply.
//
// ExporterConfigStatus reports the observed state of an ExporterConfig.
type ExporterConfigStatusApplyConfiguration struct {
	// Ready is true when referenced Secrets exist and credentials validate.
	Ready *bool `json:"ready,omitempty"`
	// Conditions is the latest available observations.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// ReferencedBy counts how many PodTraces and PodTraceSessions reference this exporter.
	ReferencedBy *int32 `json:"referencedBy,omitempty"`
	// ObservedGeneration is the most recent generation observed.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
}

// ExporterConfigStatusApplyConfiguration constructs a declarative configuration of the ExporterConfigStatus type for use with
// apply.
func ExporterConfigStatus() *ExporterConfigStatusApplyConfiguration {
	return &ExporterConfigStatusApplyConfiguration{}
}

// WithReady sets the Ready field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ready field is set to the value of the last call.
func (b *ExporterConfigStatusApplyConfiguration) WithReady(value bool) *ExporterConfigStatusApplyConfiguration {
	b.Ready = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *ExporterConfigStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *ExporterConfigStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithReferencedBy sets the ReferencedBy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReferencedBy field is set to the value of the last call.
func (b *ExporterConfigStatusApplyConfiguration) WithReferencedBy(value int32) *ExporterConfigStatusApplyConfiguration {
	b.ReferencedBy = &value
	return b
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *ExporterConfigStatusApplyConfiguration) WithObservedGeneration(value int64) *ExporterConfigStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}
