/*
Copyright 2026 Ghassan Malke.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// JaegerExporterApplyConfiguration represents a declarative configuration of the JaegerExporter type for use
// with apply.
//
// JaegerExporter configures the Jaeger exporter.
//
// Agent mode ships spans to Jaeger over OTLP/HTTP, so the endpoint must
// point at Jaeger's OTLP receiver (port 4318 by default), not the legacy
// Thrift collector endpoint. See docs/tracing-exporters.md.
type JaegerExporterApplyConfiguration struct {
	// Endpoint of Jaeger's OTLP/HTTP receiver, e.g.
	// "jaeger-collector.observability:4318".
	Endpoint *string `json:"endpoint,omitempty"`
}

// JaegerExporterApplyConfiguration constructs a declarative configuration of the JaegerExporter type for use with
// apply.
func JaegerExporter() *JaegerExporterApplyConfiguration {
	return &JaegerExporterApplyConfiguration{}
}

// WithEndpoint sets the Endpoint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Endpoint field is set to the value of the last call.
func (b *JaegerExporterApplyConfiguration) WithEndpoint(value string) *JaegerExporterApplyConfiguration {
	b.Endpoint = &value
	return b
}
