/*
Copyright 2026 Ghassan Malke.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// ObjectStoreReferenceApplyConfiguration represents a declarative configuration of the ObjectStoreReference type for use
// with apply.
//
// ObjectStoreReference names a cloud-storage destination for a session
// report. When CredentialsSecretRef is unset, the uploader uses the
// cloud SDK's default credential chain (IRSA / Workload Identity /
// Managed Identity) — the cloud-native preferred path. The explicit
// Secret is the fallback for clusters without ambient credentials.
//
// Per-backend Secret key schema (all optional — missing keys defer to
// the SDK default chain):
//
// S3:     access_key_id, secret_access_key, session_token,
// region, endpoint, force_path_style
// GCS:    service_account_json, endpoint
// Azure:  tenant_id, client_id, client_secret,
// account_key, endpoint
type ObjectStoreReferenceApplyConfiguration struct {
	// URI of the destination. Three schemes:
	//
	// s3://bucket/key-or-prefix
	// gs://bucket/key-or-prefix
	// azblob://account/container/key-or-prefix
	//
	// A trailing slash means "prefix mode" — the uploader appends a
	// per-session filename (<pod-name>-<rfc3339>.txt) and an additional
	// <key>.summary.json object. Without a trailing slash, the URI's
	// path is used verbatim as the object key.
	URI                  *string                  `json:"uri,omitempty"`
	CredentialsSecretRef *v1.LocalObjectReference `json:"credentialsSecretRef,omitempty"`
}

// ObjectStoreReferenceApplyConfiguration constructs a declarative configuration of the ObjectStoreReference type for use with
// apply.
func ObjectStoreReference() *ObjectStoreReferenceApplyConfiguration {
	return &ObjectStoreReferenceApplyConfiguration{}
}

// WithURI sets the URI field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the URI field is set to the value of the last call.
func (b *ObjectStoreReferenceApplyConfiguration) WithURI(value string) *ObjectStoreReferenceApplyConfiguration {
	b.URI = &value
	return b
}

// WithCredentialsSecretRef sets the CredentialsSecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CredentialsSecretRef field is set to the value of the last call.
func (b *ObjectStoreReferenceApplyConfiguration) WithCredentialsSecretRef(value v1.LocalObjectReference) *ObjectStoreReferenceApplyConfiguration {
	b.CredentialsSecretRef = &value
	return b
}
