/*
Copyright 2026 Ghassan Malke.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/podtrace/podtrace/api/v1alpha1"
)

// OTLPExporterApplyConfiguration represents a declarative configuration of the OTLPExporter type for use
// with apply.
//
// OTLPExporter configures the OpenTelemetry OTLP exporter.
type OTLPExporterApplyConfiguration struct {
	// Endpoint of the OTLP receiver, e.g. "otel-collector.observability:4318".
	Endpoint *string `json:"endpoint,omitempty"`
	// Protocol selects http or grpc. Defaults to http.
	Protocol *apiv1alpha1.OTLPProtocol `json:"protocol,omitempty"`
	// Insecure disables TLS. Do not use in production.
	Insecure *bool `json:"insecure,omitempty"`
	// Headers to attach to every export request. Secret-backed headers use
	// the HeadersFromSecret field.
	Headers []OTLPHeaderApplyConfiguration `json:"headers,omitempty"`
	// HeadersFromSecret pulls additional headers from a Secret in the same
	// namespace. Each key in the secret becomes a header; values are used verbatim.
	HeadersFromSecret *LocalObjectReferenceApplyConfiguration `json:"headersFromSecret,omitempty"`
}

// OTLPExporterApplyConfiguration constructs a declarative configuration of the OTLPExporter type for use with
// apply.
func OTLPExporter() *OTLPExporterApplyConfiguration {
	return &OTLPExporterApplyConfiguration{}
}

// WithEndpoint sets the Endpoint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Endpoint field is set to the value of the last call.
func (b *OTLPExporterApplyConfiguration) WithEndpoint(value string) *OTLPExporterApplyConfiguration {
	b.Endpoint = &value
	return b
}

// WithProtocol sets the Protocol field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Protocol field is set to the value of the last call.
func (b *OTLPExporterApplyConfiguration) WithProtocol(value apiv1alpha1.OTLPProtocol) *OTLPExporterApplyConfiguration {
	b.Protocol = &value
	return b
}

// WithInsecure sets the Insecure field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Insecure field is set to the value of the last call.
func (b *OTLPExporterApplyConfiguration) WithInsecure(value bool) *OTLPExporterApplyConfiguration {
	b.Insecure = &value
	return b
}

// WithHeaders adds the given value to the Headers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Headers field.
func (b *OTLPExporterApplyConfiguration) WithHeaders(values ...*OTLPHeaderApplyConfiguration) *OTLPExporterApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithHeaders")
		}
		b.Headers = append(b.Headers, *values[i])
	}
	return b
}

// WithHeadersFromSecret sets the HeadersFromSecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HeadersFromSecret field is set to the value of the last call.
func (b *OTLPExporterApplyConfiguration) WithHeadersFromSecret(value *LocalObjectReferenceApplyConfiguration) *OTLPExporterApplyConfiguration {
	b.HeadersFromSecret = value
	return b
}
