/*
Copyright 2026 Ghassan Malke.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// OTLPMetricsApplyConfiguration represents a declarative configuration of the OTLPMetrics type for use
// with apply.
//
// OTLPMetrics turns the continuous metrics plane into a second OTLP
// signal on an exporter that already carries spans.
type OTLPMetricsApplyConfiguration struct {
	// Enabled pushes metrics to the exporter's endpoint.
	Enabled *bool `json:"enabled,omitempty"`
	// Interval between pushes. Defaults to 60s, clamped to 10s-10m. Must be
	// a non-negative Go duration; an unparseable value is refused because it
	// would break the typed LIST every client-go informer performs.
	Interval *v1.Duration `json:"interval,omitempty"`
}

// OTLPMetricsApplyConfiguration constructs a declarative configuration of the OTLPMetrics type for use with
// apply.
func OTLPMetrics() *OTLPMetricsApplyConfiguration {
	return &OTLPMetricsApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *OTLPMetricsApplyConfiguration) WithEnabled(value bool) *OTLPMetricsApplyConfiguration {
	b.Enabled = &value
	return b
}

// WithInterval sets the Interval field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Interval field is set to the value of the last call.
func (b *OTLPMetricsApplyConfiguration) WithInterval(value v1.Duration) *OTLPMetricsApplyConfiguration {
	b.Interval = &value
	return b
}
