/*
Copyright 2026 Ghassan Malke.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// PodRefApplyConfiguration represents a declarative configuration of the PodRef type for use
// with apply.
//
// PodRef references a specific pod by namespace/name.
type PodRefApplyConfiguration struct {
	// Namespace is the namespace of the pod. If empty, defaults to the
	// namespace of the owning CR (for namespaced CRs).
	Namespace *string `json:"namespace,omitempty"`
	// Name is the name of the pod.
	Name *string `json:"name,omitempty"`
}

// PodRefApplyConfiguration constructs a declarative configuration of the PodRef type for use with
// apply.
func PodRef() *PodRefApplyConfiguration {
	return &PodRefApplyConfiguration{}
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *PodRefApplyConfiguration) WithNamespace(value string) *PodRefApplyConfiguration {
	b.Namespace = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *PodRefApplyConfiguration) WithName(value string) *PodRefApplyConfiguration {
	b.Name = &value
	return b
}
