/*
Copyright 2026 Ghassan Malke.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/podtrace/podtrace/api/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// PodTraceSessionSpecApplyConfiguration represents a declarative configuration of the PodTraceSessionSpec type for use
// with apply.
//
// PodTraceSessionSpec defines a bounded diagnose-mode trace. The operator
// reconciles this into one privileged Job per node hosting matched pods.
type PodTraceSessionSpecApplyConfiguration struct {
	Selector                *v1.LabelSelectorApplyConfiguration     `json:"selector,omitempty"`
	PodRefs                 []PodRefApplyConfiguration              `json:"podRefs,omitempty"`
	NamespaceSelector       *v1.LabelSelectorApplyConfiguration     `json:"namespaceSelector,omitempty"`
	ContainerName           *string                                 `json:"containerName,omitempty"`
	Duration                *metav1.Duration                        `json:"duration,omitempty"`
	Filters                 []apiv1alpha1.EventFilter               `json:"filters,omitempty"`
	ExporterRef             *LocalObjectReferenceApplyConfiguration `json:"exporterRef,omitempty"`
	Thresholds              *ThresholdsApplyConfiguration           `json:"thresholds,omitempty"`
	SamplePercent           *int32                                  `json:"samplePercent,omitempty"`
	ReportRef               *ReportReferenceApplyConfiguration      `json:"reportRef,omitempty"`
	TTLSecondsAfterFinished *int32                                  `json:"ttlSecondsAfterFinished,omitempty"`
}

// PodTraceSessionSpecApplyConfiguration constructs a declarative configuration of the PodTraceSessionSpec type for use with
// apply.
func PodTraceSessionSpec() *PodTraceSessionSpecApplyConfiguration {
	return &PodTraceSessionSpecApplyConfiguration{}
}

// WithSelector sets the Selector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Selector field is set to the value of the last call.
func (b *PodTraceSessionSpecApplyConfiguration) WithSelector(value *v1.LabelSelectorApplyConfiguration) *PodTraceSessionSpecApplyConfiguration {
	b.Selector = value
	return b
}

// WithPodRefs adds the given value to the PodRefs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the PodRefs field.
func (b *PodTraceSessionSpecApplyConfiguration) WithPodRefs(values ...*PodRefApplyConfiguration) *PodTraceSessionSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithPodRefs")
		}
		b.PodRefs = append(b.PodRefs, *values[i])
	}
	return b
}

// WithNamespaceSelector sets the NamespaceSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NamespaceSelector field is set to the value of the last call.
func (b *PodTraceSessionSpecApplyConfiguration) WithNamespaceSelector(value *v1.LabelSelectorApplyConfiguration) *PodTraceSessionSpecApplyConfiguration {
	b.NamespaceSelector = value
	return b
}

// WithContainerName sets the ContainerName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ContainerName field is set to the value of the last call.
func (b *PodTraceSessionSpecApplyConfiguration) WithContainerName(value string) *PodTraceSessionSpecApplyConfiguration {
	b.ContainerName = &value
	return b
}

// WithDuration sets the Duration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Duration field is set to the value of the last call.
func (b *PodTraceSessionSpecApplyConfiguration) WithDuration(value metav1.Duration) *PodTraceSessionSpecApplyConfiguration {
	b.Duration = &value
	return b
}

// WithFilters adds the given value to the Filters field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Filters field.
func (b *PodTraceSessionSpecApplyConfiguration) WithFilters(values ...apiv1alpha1.EventFilter) *PodTraceSessionSpecApplyConfiguration {
	for i := range values {
		b.Filters = append(b.Filters, values[i])
	}
	return b
}

// WithExporterRef sets the ExporterRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExporterRef field is set to the value of the last call.
func (b *PodTraceSessionSpecApplyConfiguration) WithExporterRef(value *LocalObjectReferenceApplyConfiguration) *PodTraceSessionSpecApplyConfiguration {
	b.ExporterRef = value
	return b
}

// WithThresholds sets the Thresholds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Thresholds field is set to the value of the last call.
func (b *PodTraceSessionSpecApplyConfiguration) WithThresholds(value *ThresholdsApplyConfiguration) *PodTraceSessionSpecApplyConfiguration {
	b.Thresholds = value
	return b
}

// WithSamplePercent sets the SamplePercent field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SamplePercent field is set to the value of the last call.
func (b *PodTraceSessionSpecApplyConfiguration) WithSamplePercent(value int32) *PodTraceSessionSpecApplyConfiguration {
	b.SamplePercent = &value
	return b
}

// WithReportRef sets the ReportRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReportRef field is set to the value of the last call.
func (b *PodTraceSessionSpecApplyConfiguration) WithReportRef(value *ReportReferenceApplyConfiguration) *PodTraceSessionSpecApplyConfiguration {
	b.ReportRef = value
	return b
}

// WithTTLSecondsAfterFinished sets the TTLSecondsAfterFinished field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TTLSecondsAfterFinished field is set to the value of the last call.
func (b *PodTraceSessionSpecApplyConfiguration) WithTTLSecondsAfterFinished(value int32) *PodTraceSessionSpecApplyConfiguration {
	b.TTLSecondsAfterFinished = &value
	return b
}
