/*
Copyright 2026 Ghassan Malke.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// PodTraceStatusApplyConfiguration represents a declarative configuration of the PodTraceStatus type for use
// with apply.
//
// PodTraceStatus reflects the observed state of a PodTrace.
type PodTraceStatusApplyConfiguration struct {
	Conditions         []v1.ConditionApplyConfiguration       `json:"conditions,omitempty"`
	NodeStatus         []PodTraceNodeStatusApplyConfiguration `json:"nodeStatus,omitempty"`
	MatchedPods        *int32                                 `json:"matchedPods,omitempty"`
	TargetNamespaces   []string                               `json:"targetNamespaces,omitempty"`
	ObservedGeneration *int64                                 `json:"observedGeneration,omitempty"`
	Policy             *PolicyStatusApplyConfiguration        `json:"policy,omitempty"`
}

// PodTraceStatusApplyConfiguration constructs a declarative configuration of the PodTraceStatus type for use with
// apply.
func PodTraceStatus() *PodTraceStatusApplyConfiguration {
	return &PodTraceStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *PodTraceStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *PodTraceStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithNodeStatus adds the given value to the NodeStatus field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the NodeStatus field.
func (b *PodTraceStatusApplyConfiguration) WithNodeStatus(values ...*PodTraceNodeStatusApplyConfiguration) *PodTraceStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithNodeStatus")
		}
		b.NodeStatus = append(b.NodeStatus, *values[i])
	}
	return b
}

// WithMatchedPods sets the MatchedPods field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MatchedPods field is set to the value of the last call.
func (b *PodTraceStatusApplyConfiguration) WithMatchedPods(value int32) *PodTraceStatusApplyConfiguration {
	b.MatchedPods = &value
	return b
}

// WithTargetNamespaces adds the given value to the TargetNamespaces field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the TargetNamespaces field.
func (b *PodTraceStatusApplyConfiguration) WithTargetNamespaces(values ...string) *PodTraceStatusApplyConfiguration {
	for i := range values {
		b.TargetNamespaces = append(b.TargetNamespaces, values[i])
	}
	return b
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *PodTraceStatusApplyConfiguration) WithObservedGeneration(value int64) *PodTraceStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithPolicy sets the Policy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Policy field is set to the value of the last call.
func (b *PodTraceStatusApplyConfiguration) WithPolicy(value *PolicyStatusApplyConfiguration) *PodTraceStatusApplyConfiguration {
	b.Policy = value
	return b
}
