/*
Copyright 2026 Ghassan Malke.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/podtrace/podtrace/api/v1alpha1"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// PodTraceSpecApplyConfiguration represents a declarative configuration of the PodTraceSpec type for use
// with apply.
//
// PodTraceSpec defines a continuous, realtime tracing intent over a set of pods.
// PodTrace is the continuous-observability counterpart of PodTraceSession: it
// has no bounded duration and remains active until the resource is deleted or
// paused.
type PodTraceSpecApplyConfiguration struct {
	Selector          *v1.LabelSelectorApplyConfiguration     `json:"selector,omitempty"`
	PodRefs           []PodRefApplyConfiguration              `json:"podRefs,omitempty"`
	NamespaceSelector *v1.LabelSelectorApplyConfiguration     `json:"namespaceSelector,omitempty"`
	ContainerName     *string                                 `json:"containerName,omitempty"`
	Filters           []apiv1alpha1.EventFilter               `json:"filters,omitempty"`
	ExporterRef       *LocalObjectReferenceApplyConfiguration `json:"exporterRef,omitempty"`
	Thresholds        *ThresholdsApplyConfiguration           `json:"thresholds,omitempty"`
	SamplePercent     *int32                                  `json:"samplePercent,omitempty"`
	Paused            *bool                                   `json:"paused,omitempty"`
}

// PodTraceSpecApplyConfiguration constructs a declarative configuration of the PodTraceSpec type for use with
// apply.
func PodTraceSpec() *PodTraceSpecApplyConfiguration {
	return &PodTraceSpecApplyConfiguration{}
}

// WithSelector sets the Selector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Selector field is set to the value of the last call.
func (b *PodTraceSpecApplyConfiguration) WithSelector(value *v1.LabelSelectorApplyConfiguration) *PodTraceSpecApplyConfiguration {
	b.Selector = value
	return b
}

// WithPodRefs adds the given value to the PodRefs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the PodRefs field.
func (b *PodTraceSpecApplyConfiguration) WithPodRefs(values ...*PodRefApplyConfiguration) *PodTraceSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithPodRefs")
		}
		b.PodRefs = append(b.PodRefs, *values[i])
	}
	return b
}

// WithNamespaceSelector sets the NamespaceSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NamespaceSelector field is set to the value of the last call.
func (b *PodTraceSpecApplyConfiguration) WithNamespaceSelector(value *v1.LabelSelectorApplyConfiguration) *PodTraceSpecApplyConfiguration {
	b.NamespaceSelector = value
	return b
}

// WithContainerName sets the ContainerName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ContainerName field is set to the value of the last call.
func (b *PodTraceSpecApplyConfiguration) WithContainerName(value string) *PodTraceSpecApplyConfiguration {
	b.ContainerName = &value
	return b
}

// WithFilters adds the given value to the Filters field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Filters field.
func (b *PodTraceSpecApplyConfiguration) WithFilters(values ...apiv1alpha1.EventFilter) *PodTraceSpecApplyConfiguration {
	for i := range values {
		b.Filters = append(b.Filters, values[i])
	}
	return b
}

// WithExporterRef sets the ExporterRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExporterRef field is set to the value of the last call.
func (b *PodTraceSpecApplyConfiguration) WithExporterRef(value *LocalObjectReferenceApplyConfiguration) *PodTraceSpecApplyConfiguration {
	b.ExporterRef = value
	return b
}

// WithThresholds sets the Thresholds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Thresholds field is set to the value of the last call.
func (b *PodTraceSpecApplyConfiguration) WithThresholds(value *ThresholdsApplyConfiguration) *PodTraceSpecApplyConfiguration {
	b.Thresholds = value
	return b
}

// WithSamplePercent sets the SamplePercent field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SamplePercent field is set to the value of the last call.
func (b *PodTraceSpecApplyConfiguration) WithSamplePercent(value int32) *PodTraceSpecApplyConfiguration {
	b.SamplePercent = &value
	return b
}

// WithPaused sets the Paused field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Paused field is set to the value of the last call.
func (b *PodTraceSpecApplyConfiguration) WithPaused(value bool) *PodTraceSpecApplyConfiguration {
	b.Paused = &value
	return b
}
