/*
Copyright 2026 Ghassan Malke.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/podtrace/podtrace/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// PodTraceSessionStatusApplyConfiguration represents a declarative configuration of the PodTraceSessionStatus type for use
// with apply.
//
// PodTraceSessionStatus reflects the observed state of a PodTraceSession.
type PodTraceSessionStatusApplyConfiguration struct {
	State               *apiv1alpha1.SessionState            `json:"state,omitempty"`
	StartTime           *v1.Time                             `json:"startTime,omitempty"`
	CompletionTime      *v1.Time                             `json:"completionTime,omitempty"`
	Jobs                []SessionJobRefApplyConfiguration    `json:"jobs,omitempty"`
	Summary             *SessionSummaryApplyConfiguration    `json:"summary,omitempty"`
	TargetNamespaces    []string                             `json:"targetNamespaces,omitempty"`
	ReportLocation      *string                              `json:"reportLocation,omitempty"`
	ReportFailureReason *apiv1alpha1.ReportFailureReason     `json:"reportFailureReason,omitempty"`
	ReportAttempts      *int32                               `json:"reportAttempts,omitempty"`
	Conditions          []metav1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	ObservedGeneration  *int64                               `json:"observedGeneration,omitempty"`
	Policy              *PolicyStatusApplyConfiguration      `json:"policy,omitempty"`
}

// PodTraceSessionStatusApplyConfiguration constructs a declarative configuration of the PodTraceSessionStatus type for use with
// apply.
func PodTraceSessionStatus() *PodTraceSessionStatusApplyConfiguration {
	return &PodTraceSessionStatusApplyConfiguration{}
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *PodTraceSessionStatusApplyConfiguration) WithState(value apiv1alpha1.SessionState) *PodTraceSessionStatusApplyConfiguration {
	b.State = &value
	return b
}

// WithStartTime sets the StartTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StartTime field is set to the value of the last call.
func (b *PodTraceSessionStatusApplyConfiguration) WithStartTime(value v1.Time) *PodTraceSessionStatusApplyConfiguration {
	b.StartTime = &value
	return b
}

// WithCompletionTime sets the CompletionTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CompletionTime field is set to the value of the last call.
func (b *PodTraceSessionStatusApplyConfiguration) WithCompletionTime(value v1.Time) *PodTraceSessionStatusApplyConfiguration {
	b.CompletionTime = &value
	return b
}

// WithJobs adds the given value to the Jobs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Jobs field.
func (b *PodTraceSessionStatusApplyConfiguration) WithJobs(values ...*SessionJobRefApplyConfiguration) *PodTraceSessionStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithJobs")
		}
		b.Jobs = append(b.Jobs, *values[i])
	}
	return b
}

// WithSummary sets the Summary field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Summary field is set to the value of the last call.
func (b *PodTraceSessionStatusApplyConfiguration) WithSummary(value *SessionSummaryApplyConfiguration) *PodTraceSessionStatusApplyConfiguration {
	b.Summary = value
	return b
}

// WithTargetNamespaces adds the given value to the TargetNamespaces field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the TargetNamespaces field.
func (b *PodTraceSessionStatusApplyConfiguration) WithTargetNamespaces(values ...string) *PodTraceSessionStatusApplyConfiguration {
	for i := range values {
		b.TargetNamespaces = append(b.TargetNamespaces, values[i])
	}
	return b
}

// WithReportLocation sets the ReportLocation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReportLocation field is set to the value of the last call.
func (b *PodTraceSessionStatusApplyConfiguration) WithReportLocation(value string) *PodTraceSessionStatusApplyConfiguration {
	b.ReportLocation = &value
	return b
}

// WithReportFailureReason sets the ReportFailureReason field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReportFailureReason field is set to the value of the last call.
func (b *PodTraceSessionStatusApplyConfiguration) WithReportFailureReason(value apiv1alpha1.ReportFailureReason) *PodTraceSessionStatusApplyConfiguration {
	b.ReportFailureReason = &value
	return b
}

// WithReportAttempts sets the ReportAttempts field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReportAttempts field is set to the value of the last call.
func (b *PodTraceSessionStatusApplyConfiguration) WithReportAttempts(value int32) *PodTraceSessionStatusApplyConfiguration {
	b.ReportAttempts = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *PodTraceSessionStatusApplyConfiguration) WithConditions(values ...*metav1.ConditionApplyConfiguration) *PodTraceSessionStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *PodTraceSessionStatusApplyConfiguration) WithObservedGeneration(value int64) *PodTraceSessionStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}

// WithPolicy sets the Policy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Policy field is set to the value of the last call.
func (b *PodTraceSessionStatusApplyConfiguration) WithPolicy(value *PolicyStatusApplyConfiguration) *PodTraceSessionStatusApplyConfiguration {
	b.Policy = value
	return b
}
