/*
Copyright 2026 Ghassan Malke.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/podtrace/podtrace/api/v1alpha1"
)

// PodTraceScheduleSpecApplyConfiguration represents a declarative configuration of the PodTraceScheduleSpec type for use
// with apply.
//
// PodTraceScheduleSpec describes a recurring PodTraceSession schedule.
type PodTraceScheduleSpecApplyConfiguration struct {
	// Schedule is the cron expression that triggers session creation.
	// Accepts the standard 5-field form ("*/5 * * * *") and the 6-field
	// form with leading seconds ("0 */5 * * * *"). Descriptors such as
	// "@hourly", "@daily" and "@every 5m" are also accepted.
	Schedule *string `json:"schedule,omitempty"`
	// TimeZone is an IANA time-zone name (e.g. "Europe/Amsterdam") used
	// to interpret Schedule.
	TimeZone                       *string                                        `json:"timeZone,omitempty"`
	ConcurrencyPolicy              *apiv1alpha1.ConcurrencyPolicy                 `json:"concurrencyPolicy,omitempty"`
	StartingDeadlineSeconds        *int64                                         `json:"startingDeadlineSeconds,omitempty"`
	SuccessfulSessionsHistoryLimit *int32                                         `json:"successfulSessionsHistoryLimit,omitempty"`
	FailedSessionsHistoryLimit     *int32                                         `json:"failedSessionsHistoryLimit,omitempty"`
	Suspend                        *bool                                          `json:"suspend,omitempty"`
	MaxActiveSessions              *int32                                         `json:"maxActiveSessions,omitempty"`
	SessionTemplate                *PodTraceSessionTemplateSpecApplyConfiguration `json:"sessionTemplate,omitempty"`
}

// PodTraceScheduleSpecApplyConfiguration constructs a declarative configuration of the PodTraceScheduleSpec type for use with
// apply.
func PodTraceScheduleSpec() *PodTraceScheduleSpecApplyConfiguration {
	return &PodTraceScheduleSpecApplyConfiguration{}
}

// WithSchedule sets the Schedule field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Schedule field is set to the value of the last call.
func (b *PodTraceScheduleSpecApplyConfiguration) WithSchedule(value string) *PodTraceScheduleSpecApplyConfiguration {
	b.Schedule = &value
	return b
}

// WithTimeZone sets the TimeZone field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TimeZone field is set to the value of the last call.
func (b *PodTraceScheduleSpecApplyConfiguration) WithTimeZone(value string) *PodTraceScheduleSpecApplyConfiguration {
	b.TimeZone = &value
	return b
}

// WithConcurrencyPolicy sets the ConcurrencyPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConcurrencyPolicy field is set to the value of the last call.
func (b *PodTraceScheduleSpecApplyConfiguration) WithConcurrencyPolicy(value apiv1alpha1.ConcurrencyPolicy) *PodTraceScheduleSpecApplyConfiguration {
	b.ConcurrencyPolicy = &value
	return b
}

// WithStartingDeadlineSeconds sets the StartingDeadlineSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StartingDeadlineSeconds field is set to the value of the last call.
func (b *PodTraceScheduleSpecApplyConfiguration) WithStartingDeadlineSeconds(value int64) *PodTraceScheduleSpecApplyConfiguration {
	b.StartingDeadlineSeconds = &value
	return b
}

// WithSuccessfulSessionsHistoryLimit sets the SuccessfulSessionsHistoryLimit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SuccessfulSessionsHistoryLimit field is set to the value of the last call.
func (b *PodTraceScheduleSpecApplyConfiguration) WithSuccessfulSessionsHistoryLimit(value int32) *PodTraceScheduleSpecApplyConfiguration {
	b.SuccessfulSessionsHistoryLimit = &value
	return b
}

// WithFailedSessionsHistoryLimit sets the FailedSessionsHistoryLimit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FailedSessionsHistoryLimit field is set to the value of the last call.
func (b *PodTraceScheduleSpecApplyConfiguration) WithFailedSessionsHistoryLimit(value int32) *PodTraceScheduleSpecApplyConfiguration {
	b.FailedSessionsHistoryLimit = &value
	return b
}

// WithSuspend sets the Suspend field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Suspend field is set to the value of the last call.
func (b *PodTraceScheduleSpecApplyConfiguration) WithSuspend(value bool) *PodTraceScheduleSpecApplyConfiguration {
	b.Suspend = &value
	return b
}

// WithMaxActiveSessions sets the MaxActiveSessions field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxActiveSessions field is set to the value of the last call.
func (b *PodTraceScheduleSpecApplyConfiguration) WithMaxActiveSessions(value int32) *PodTraceScheduleSpecApplyConfiguration {
	b.MaxActiveSessions = &value
	return b
}

// WithSessionTemplate sets the SessionTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SessionTemplate field is set to the value of the last call.
func (b *PodTraceScheduleSpecApplyConfiguration) WithSessionTemplate(value *PodTraceSessionTemplateSpecApplyConfiguration) *PodTraceScheduleSpecApplyConfiguration {
	b.SessionTemplate = value
	return b
}
