/*
Copyright 2026 Ghassan Malke.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/podtrace/podtrace/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// PodTraceNodeStatusApplyConfiguration represents a declarative configuration of the PodTraceNodeStatus type for use
// with apply.
//
// PodTraceNodeStatus reports one agent's view of this PodTrace.
type PodTraceNodeStatusApplyConfiguration struct {
	Node          *string                       `json:"node,omitempty"`
	Ready         *bool                         `json:"ready,omitempty"`
	ActiveCgroups *int32                        `json:"activeCgroups,omitempty"`
	EventsTotal   *int64                        `json:"eventsTotal,omitempty"`
	DroppedEvents *int64                        `json:"droppedEvents,omitempty"`
	LastHeartbeat *v1.Time                      `json:"lastHeartbeat,omitempty"`
	Message       *string                       `json:"message,omitempty"`
	Reason        *apiv1alpha1.NodeStatusReason `json:"reason,omitempty"`
	PolicyHash    *string                       `json:"policyHash,omitempty"`
}

// PodTraceNodeStatusApplyConfiguration constructs a declarative configuration of the PodTraceNodeStatus type for use with
// apply.
func PodTraceNodeStatus() *PodTraceNodeStatusApplyConfiguration {
	return &PodTraceNodeStatusApplyConfiguration{}
}

// WithNode sets the Node field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Node field is set to the value of the last call.
func (b *PodTraceNodeStatusApplyConfiguration) WithNode(value string) *PodTraceNodeStatusApplyConfiguration {
	b.Node = &value
	return b
}

// WithReady sets the Ready field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Ready field is set to the value of the last call.
func (b *PodTraceNodeStatusApplyConfiguration) WithReady(value bool) *PodTraceNodeStatusApplyConfiguration {
	b.Ready = &value
	return b
}

// WithActiveCgroups sets the ActiveCgroups field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ActiveCgroups field is set to the value of the last call.
func (b *PodTraceNodeStatusApplyConfiguration) WithActiveCgroups(value int32) *PodTraceNodeStatusApplyConfiguration {
	b.ActiveCgroups = &value
	return b
}

// WithEventsTotal sets the EventsTotal field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EventsTotal field is set to the value of the last call.
func (b *PodTraceNodeStatusApplyConfiguration) WithEventsTotal(value int64) *PodTraceNodeStatusApplyConfiguration {
	b.EventsTotal = &value
	return b
}

// WithDroppedEvents sets the DroppedEvents field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DroppedEvents field is set to the value of the last call.
func (b *PodTraceNodeStatusApplyConfiguration) WithDroppedEvents(value int64) *PodTraceNodeStatusApplyConfiguration {
	b.DroppedEvents = &value
	return b
}

// WithLastHeartbeat sets the LastHeartbeat field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastHeartbeat field is set to the value of the last call.
func (b *PodTraceNodeStatusApplyConfiguration) WithLastHeartbeat(value v1.Time) *PodTraceNodeStatusApplyConfiguration {
	b.LastHeartbeat = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *PodTraceNodeStatusApplyConfiguration) WithMessage(value string) *PodTraceNodeStatusApplyConfiguration {
	b.Message = &value
	return b
}

// WithReason sets the Reason field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Reason field is set to the value of the last call.
func (b *PodTraceNodeStatusApplyConfiguration) WithReason(value apiv1alpha1.NodeStatusReason) *PodTraceNodeStatusApplyConfiguration {
	b.Reason = &value
	return b
}

// WithPolicyHash sets the PolicyHash field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PolicyHash field is set to the value of the last call.
func (b *PodTraceNodeStatusApplyConfiguration) WithPolicyHash(value string) *PodTraceNodeStatusApplyConfiguration {
	b.PolicyHash = &value
	return b
}
