/*
Copyright 2026 Ghassan Malke.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	applyconfigurationsmetav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// PodTraceScheduleStatusApplyConfiguration represents a declarative configuration of the PodTraceScheduleStatus type for use
// with apply.
//
// PodTraceScheduleStatus reflects the observed state of a
// PodTraceSchedule.
type PodTraceScheduleStatusApplyConfiguration struct {
	Active             []v1.ObjectReference                                    `json:"active,omitempty"`
	LastScheduleTime   *metav1.Time                                            `json:"lastScheduleTime,omitempty"`
	LastSuccessfulTime *metav1.Time                                            `json:"lastSuccessfulTime,omitempty"`
	Conditions         []applyconfigurationsmetav1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	ObservedGeneration *int64                                                  `json:"observedGeneration,omitempty"`
}

// PodTraceScheduleStatusApplyConfiguration constructs a declarative configuration of the PodTraceScheduleStatus type for use with
// apply.
func PodTraceScheduleStatus() *PodTraceScheduleStatusApplyConfiguration {
	return &PodTraceScheduleStatusApplyConfiguration{}
}

// WithActive adds the given value to the Active field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Active field.
func (b *PodTraceScheduleStatusApplyConfiguration) WithActive(values ...v1.ObjectReference) *PodTraceScheduleStatusApplyConfiguration {
	for i := range values {
		b.Active = append(b.Active, values[i])
	}
	return b
}

// WithLastScheduleTime sets the LastScheduleTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastScheduleTime field is set to the value of the last call.
func (b *PodTraceScheduleStatusApplyConfiguration) WithLastScheduleTime(value metav1.Time) *PodTraceScheduleStatusApplyConfiguration {
	b.LastScheduleTime = &value
	return b
}

// WithLastSuccessfulTime sets the LastSuccessfulTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastSuccessfulTime field is set to the value of the last call.
func (b *PodTraceScheduleStatusApplyConfiguration) WithLastSuccessfulTime(value metav1.Time) *PodTraceScheduleStatusApplyConfiguration {
	b.LastSuccessfulTime = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *PodTraceScheduleStatusApplyConfiguration) WithConditions(values ...*applyconfigurationsmetav1.ConditionApplyConfiguration) *PodTraceScheduleStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *PodTraceScheduleStatusApplyConfiguration) WithObservedGeneration(value int64) *PodTraceScheduleStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}
