/*
Copyright 2026 Ghassan Malke.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/podtrace/podtrace/api/v1alpha1"
)

// PolicyStatusApplyConfiguration represents a declarative configuration of the PolicyStatus type for use
// with apply.
//
// PolicyStatus is the operator-side view of the effective policy a
// PodTrace imposes on the bundle.
type PolicyStatusApplyConfiguration struct {
	EffectiveSampleRate *int32                        `json:"effectiveSampleRate,omitempty"`
	Filters             []apiv1alpha1.EventFilter     `json:"filters,omitempty"`
	Thresholds          *ThresholdsApplyConfiguration `json:"thresholds,omitempty"`
	Hash                *string                       `json:"hash,omitempty"`
	Generation          *int64                        `json:"generation,omitempty"`
}

// PolicyStatusApplyConfiguration constructs a declarative configuration of the PolicyStatus type for use with
// apply.
func PolicyStatus() *PolicyStatusApplyConfiguration {
	return &PolicyStatusApplyConfiguration{}
}

// WithEffectiveSampleRate sets the EffectiveSampleRate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EffectiveSampleRate field is set to the value of the last call.
func (b *PolicyStatusApplyConfiguration) WithEffectiveSampleRate(value int32) *PolicyStatusApplyConfiguration {
	b.EffectiveSampleRate = &value
	return b
}

// WithFilters adds the given value to the Filters field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Filters field.
func (b *PolicyStatusApplyConfiguration) WithFilters(values ...apiv1alpha1.EventFilter) *PolicyStatusApplyConfiguration {
	for i := range values {
		b.Filters = append(b.Filters, values[i])
	}
	return b
}

// WithThresholds sets the Thresholds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Thresholds field is set to the value of the last call.
func (b *PolicyStatusApplyConfiguration) WithThresholds(value *ThresholdsApplyConfiguration) *PolicyStatusApplyConfiguration {
	b.Thresholds = value
	return b
}

// WithHash sets the Hash field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Hash field is set to the value of the last call.
func (b *PolicyStatusApplyConfiguration) WithHash(value string) *PolicyStatusApplyConfiguration {
	b.Hash = &value
	return b
}

// WithGeneration sets the Generation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Generation field is set to the value of the last call.
func (b *PolicyStatusApplyConfiguration) WithGeneration(value int64) *PolicyStatusApplyConfiguration {
	b.Generation = &value
	return b
}
