/*
Copyright 2026 Ghassan Malke.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// RedactionRuleApplyConfiguration represents a declarative configuration of the RedactionRule type for use
// with apply.
//
// RedactionRule is a single user-supplied redaction pattern.
type RedactionRuleApplyConfiguration struct {
	Name    *string `json:"name,omitempty"`
	Pattern *string `json:"pattern,omitempty"`
	Replace *string `json:"replace,omitempty"`
}

// RedactionRuleApplyConfiguration constructs a declarative configuration of the RedactionRule type for use with
// apply.
func RedactionRule() *RedactionRuleApplyConfiguration {
	return &RedactionRuleApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *RedactionRuleApplyConfiguration) WithName(value string) *RedactionRuleApplyConfiguration {
	b.Name = &value
	return b
}

// WithPattern sets the Pattern field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Pattern field is set to the value of the last call.
func (b *RedactionRuleApplyConfiguration) WithPattern(value string) *RedactionRuleApplyConfiguration {
	b.Pattern = &value
	return b
}

// WithReplace sets the Replace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replace field is set to the value of the last call.
func (b *RedactionRuleApplyConfiguration) WithReplace(value string) *RedactionRuleApplyConfiguration {
	b.Replace = &value
	return b
}
