/*
Copyright 2026 Ghassan Malke.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// RedactionSpecApplyConfiguration represents a declarative configuration of the RedactionSpec type for use
// with apply.
//
// RedactionSpec configures PII redaction applied to event Target and Details
// fields in the tracer, before any exporter or report sink receives them.
type RedactionSpecApplyConfiguration struct {
	Enabled        *bool                             `json:"enabled,omitempty"`
	RedactDNSNames *bool                             `json:"redactDNSNames,omitempty"`
	CustomRules    []RedactionRuleApplyConfiguration `json:"customRules,omitempty"`
}

// RedactionSpecApplyConfiguration constructs a declarative configuration of the RedactionSpec type for use with
// apply.
func RedactionSpec() *RedactionSpecApplyConfiguration {
	return &RedactionSpecApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *RedactionSpecApplyConfiguration) WithEnabled(value bool) *RedactionSpecApplyConfiguration {
	b.Enabled = &value
	return b
}

// WithRedactDNSNames sets the RedactDNSNames field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RedactDNSNames field is set to the value of the last call.
func (b *RedactionSpecApplyConfiguration) WithRedactDNSNames(value bool) *RedactionSpecApplyConfiguration {
	b.RedactDNSNames = &value
	return b
}

// WithCustomRules adds the given value to the CustomRules field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the CustomRules field.
func (b *RedactionSpecApplyConfiguration) WithCustomRules(values ...*RedactionRuleApplyConfiguration) *RedactionSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithCustomRules")
		}
		b.CustomRules = append(b.CustomRules, *values[i])
	}
	return b
}
