/*
Copyright 2026 Ghassan Malke.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// ReportReferenceApplyConfiguration represents a declarative configuration of the ReportReference type for use
// with apply.
//
// ReportReference describes where a session's diagnose report is persisted.
// Exactly one sink should be set.
type ReportReferenceApplyConfiguration struct {
	// ConfigMap in the same namespace as the session. The operator will
	// create/update it with the report payload. Use this sink for small
	// reports; ConfigMaps are capped at 1MiB of data by etcd.
	ConfigMap *v1.LocalObjectReference `json:"configMap,omitempty"`
	// Secret in the same namespace as the session. Prefer this sink when the
	// report may contain sensitive hostnames/paths/payloads.
	Secret *v1.LocalObjectReference `json:"secret,omitempty"`
	// ObjectStore uploads the report to a cloud bucket (s3, gs, azblob).
	// Use this sink for reports that may exceed the 1MiB ConfigMap/Secret
	// limit. Requires the session pod to be on a Kubernetes 1.29+ cluster
	// so the native sidecar restartPolicy is honoured.
	ObjectStore *ObjectStoreReferenceApplyConfiguration `json:"objectStore,omitempty"`
}

// ReportReferenceApplyConfiguration constructs a declarative configuration of the ReportReference type for use with
// apply.
func ReportReference() *ReportReferenceApplyConfiguration {
	return &ReportReferenceApplyConfiguration{}
}

// WithConfigMap sets the ConfigMap field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConfigMap field is set to the value of the last call.
func (b *ReportReferenceApplyConfiguration) WithConfigMap(value v1.LocalObjectReference) *ReportReferenceApplyConfiguration {
	b.ConfigMap = &value
	return b
}

// WithSecret sets the Secret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Secret field is set to the value of the last call.
func (b *ReportReferenceApplyConfiguration) WithSecret(value v1.LocalObjectReference) *ReportReferenceApplyConfiguration {
	b.Secret = &value
	return b
}

// WithObjectStore sets the ObjectStore field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObjectStore field is set to the value of the last call.
func (b *ReportReferenceApplyConfiguration) WithObjectStore(value *ObjectStoreReferenceApplyConfiguration) *ReportReferenceApplyConfiguration {
	b.ObjectStore = value
	return b
}
