/*
Copyright 2026 Ghassan Malke.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// SessionSummaryApplyConfiguration represents a declarative configuration of the SessionSummary type for use
// with apply.
//
// SessionSummary is a compact roll-up of what the session observed.
type SessionSummaryApplyConfiguration struct {
	TotalEvents    *int64 `json:"totalEvents,omitempty"`
	DNSEvents      *int64 `json:"dnsEvents,omitempty"`
	NetEvents      *int64 `json:"netEvents,omitempty"`
	FSEvents       *int64 `json:"fsEvents,omitempty"`
	CPUEvents      *int64 `json:"cpuEvents,omitempty"`
	ProcEvents     *int64 `json:"procEvents,omitempty"`
	ErrorsDetected *int32 `json:"errorsDetected,omitempty"`
}

// SessionSummaryApplyConfiguration constructs a declarative configuration of the SessionSummary type for use with
// apply.
func SessionSummary() *SessionSummaryApplyConfiguration {
	return &SessionSummaryApplyConfiguration{}
}

// WithTotalEvents sets the TotalEvents field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TotalEvents field is set to the value of the last call.
func (b *SessionSummaryApplyConfiguration) WithTotalEvents(value int64) *SessionSummaryApplyConfiguration {
	b.TotalEvents = &value
	return b
}

// WithDNSEvents sets the DNSEvents field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DNSEvents field is set to the value of the last call.
func (b *SessionSummaryApplyConfiguration) WithDNSEvents(value int64) *SessionSummaryApplyConfiguration {
	b.DNSEvents = &value
	return b
}

// WithNetEvents sets the NetEvents field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NetEvents field is set to the value of the last call.
func (b *SessionSummaryApplyConfiguration) WithNetEvents(value int64) *SessionSummaryApplyConfiguration {
	b.NetEvents = &value
	return b
}

// WithFSEvents sets the FSEvents field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FSEvents field is set to the value of the last call.
func (b *SessionSummaryApplyConfiguration) WithFSEvents(value int64) *SessionSummaryApplyConfiguration {
	b.FSEvents = &value
	return b
}

// WithCPUEvents sets the CPUEvents field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CPUEvents field is set to the value of the last call.
func (b *SessionSummaryApplyConfiguration) WithCPUEvents(value int64) *SessionSummaryApplyConfiguration {
	b.CPUEvents = &value
	return b
}

// WithProcEvents sets the ProcEvents field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProcEvents field is set to the value of the last call.
func (b *SessionSummaryApplyConfiguration) WithProcEvents(value int64) *SessionSummaryApplyConfiguration {
	b.ProcEvents = &value
	return b
}

// WithErrorsDetected sets the ErrorsDetected field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ErrorsDetected field is set to the value of the last call.
func (b *SessionSummaryApplyConfiguration) WithErrorsDetected(value int32) *SessionSummaryApplyConfiguration {
	b.ErrorsDetected = &value
	return b
}
