/*
Copyright 2026 Ghassan Malke.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// SessionJobRefApplyConfiguration represents a declarative configuration of the SessionJobRef type for use
// with apply.
//
// SessionJobRef describes a child Job created by the session reconciler.
type SessionJobRefApplyConfiguration struct {
	Node           *string  `json:"node,omitempty"`
	Name           *string  `json:"name,omitempty"`
	Completed      *bool    `json:"completed,omitempty"`
	EventCount     *int64   `json:"eventCount,omitempty"`
	StartTime      *v1.Time `json:"startTime,omitempty"`
	CompletionTime *v1.Time `json:"completionTime,omitempty"`
	Message        *string  `json:"message,omitempty"`
}

// SessionJobRefApplyConfiguration constructs a declarative configuration of the SessionJobRef type for use with
// apply.
func SessionJobRef() *SessionJobRefApplyConfiguration {
	return &SessionJobRefApplyConfiguration{}
}

// WithNode sets the Node field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Node field is set to the value of the last call.
func (b *SessionJobRefApplyConfiguration) WithNode(value string) *SessionJobRefApplyConfiguration {
	b.Node = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *SessionJobRefApplyConfiguration) WithName(value string) *SessionJobRefApplyConfiguration {
	b.Name = &value
	return b
}

// WithCompleted sets the Completed field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Completed field is set to the value of the last call.
func (b *SessionJobRefApplyConfiguration) WithCompleted(value bool) *SessionJobRefApplyConfiguration {
	b.Completed = &value
	return b
}

// WithEventCount sets the EventCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EventCount field is set to the value of the last call.
func (b *SessionJobRefApplyConfiguration) WithEventCount(value int64) *SessionJobRefApplyConfiguration {
	b.EventCount = &value
	return b
}

// WithStartTime sets the StartTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StartTime field is set to the value of the last call.
func (b *SessionJobRefApplyConfiguration) WithStartTime(value v1.Time) *SessionJobRefApplyConfiguration {
	b.StartTime = &value
	return b
}

// WithCompletionTime sets the CompletionTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CompletionTime field is set to the value of the last call.
func (b *SessionJobRefApplyConfiguration) WithCompletionTime(value v1.Time) *SessionJobRefApplyConfiguration {
	b.CompletionTime = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *SessionJobRefApplyConfiguration) WithMessage(value string) *SessionJobRefApplyConfiguration {
	b.Message = &value
	return b
}
