/*
Copyright 2026 Ghassan Malke.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// SessionRuntimeSpecApplyConfiguration represents a declarative configuration of the SessionRuntimeSpec type for use
// with apply.
//
// SessionRuntimeSpec tunes the per-session Job pods the operator creates.
type SessionRuntimeSpecApplyConfiguration struct {
	Resources                   *v1.ResourceRequirements `json:"resources,omitempty"`
	TTLSecondsAfterFinished     *int32                   `json:"ttlSecondsAfterFinished,omitempty"`
	ActiveDeadlineSecondsOffset *int32                   `json:"activeDeadlineSecondsOffset,omitempty"`
	BackoffLimit                *int32                   `json:"backoffLimit,omitempty"`
	MaxDuration                 *metav1.Duration         `json:"maxDuration,omitempty"`
	SidecarUploader             *bool                    `json:"sidecarUploader,omitempty"`
}

// SessionRuntimeSpecApplyConfiguration constructs a declarative configuration of the SessionRuntimeSpec type for use with
// apply.
func SessionRuntimeSpec() *SessionRuntimeSpecApplyConfiguration {
	return &SessionRuntimeSpecApplyConfiguration{}
}

// WithResources sets the Resources field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resources field is set to the value of the last call.
func (b *SessionRuntimeSpecApplyConfiguration) WithResources(value v1.ResourceRequirements) *SessionRuntimeSpecApplyConfiguration {
	b.Resources = &value
	return b
}

// WithTTLSecondsAfterFinished sets the TTLSecondsAfterFinished field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TTLSecondsAfterFinished field is set to the value of the last call.
func (b *SessionRuntimeSpecApplyConfiguration) WithTTLSecondsAfterFinished(value int32) *SessionRuntimeSpecApplyConfiguration {
	b.TTLSecondsAfterFinished = &value
	return b
}

// WithActiveDeadlineSecondsOffset sets the ActiveDeadlineSecondsOffset field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ActiveDeadlineSecondsOffset field is set to the value of the last call.
func (b *SessionRuntimeSpecApplyConfiguration) WithActiveDeadlineSecondsOffset(value int32) *SessionRuntimeSpecApplyConfiguration {
	b.ActiveDeadlineSecondsOffset = &value
	return b
}

// WithBackoffLimit sets the BackoffLimit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BackoffLimit field is set to the value of the last call.
func (b *SessionRuntimeSpecApplyConfiguration) WithBackoffLimit(value int32) *SessionRuntimeSpecApplyConfiguration {
	b.BackoffLimit = &value
	return b
}

// WithMaxDuration sets the MaxDuration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxDuration field is set to the value of the last call.
func (b *SessionRuntimeSpecApplyConfiguration) WithMaxDuration(value metav1.Duration) *SessionRuntimeSpecApplyConfiguration {
	b.MaxDuration = &value
	return b
}

// WithSidecarUploader sets the SidecarUploader field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SidecarUploader field is set to the value of the last call.
func (b *SessionRuntimeSpecApplyConfiguration) WithSidecarUploader(value bool) *SessionRuntimeSpecApplyConfiguration {
	b.SidecarUploader = &value
	return b
}
