/*
Copyright 2026 Ghassan Malke.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// SessionSummaryApplyConfiguration represents a declarative configuration of the SessionSummary type for use
// with apply.
//
// SessionSummary is a compact roll-up of what the session observed.
type SessionSummaryApplyConfiguration struct {
	TotalEvents    *int64           `json:"totalEvents,omitempty"`
	EventsByFilter map[string]int64 `json:"eventsByFilter,omitempty"`
	ErrorsDetected *int32           `json:"errorsDetected,omitempty"`
}

// SessionSummaryApplyConfiguration constructs a declarative configuration of the SessionSummary type for use with
// apply.
func SessionSummary() *SessionSummaryApplyConfiguration {
	return &SessionSummaryApplyConfiguration{}
}

// WithTotalEvents sets the TotalEvents field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TotalEvents field is set to the value of the last call.
func (b *SessionSummaryApplyConfiguration) WithTotalEvents(value int64) *SessionSummaryApplyConfiguration {
	b.TotalEvents = &value
	return b
}

// WithEventsByFilter puts the entries into the EventsByFilter field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the EventsByFilter field,
// overwriting an existing map entries in EventsByFilter field with the same key.
func (b *SessionSummaryApplyConfiguration) WithEventsByFilter(entries map[string]int64) *SessionSummaryApplyConfiguration {
	if b.EventsByFilter == nil && len(entries) > 0 {
		b.EventsByFilter = make(map[string]int64, len(entries))
	}
	for k, v := range entries {
		b.EventsByFilter[k] = v
	}
	return b
}

// WithErrorsDetected sets the ErrorsDetected field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ErrorsDetected field is set to the value of the last call.
func (b *SessionSummaryApplyConfiguration) WithErrorsDetected(value int32) *SessionSummaryApplyConfiguration {
	b.ErrorsDetected = &value
	return b
}
