/*
Copyright 2026 Ghassan Malke.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// SplunkExporterApplyConfiguration represents a declarative configuration of the SplunkExporter type for use
// with apply.
//
// SplunkExporter configures the Splunk HEC exporter.
type SplunkExporterApplyConfiguration struct {
	// Endpoint of the Splunk HEC receiver.
	Endpoint *string `json:"endpoint,omitempty"`
	// TokenSecretRef references the Splunk HEC token in a Secret in the
	// same namespace as the ExporterConfig.
	TokenSecretRef *SecretKeySelectorApplyConfiguration `json:"tokenSecretRef,omitempty"`
}

// SplunkExporterApplyConfiguration constructs a declarative configuration of the SplunkExporter type for use with
// apply.
func SplunkExporter() *SplunkExporterApplyConfiguration {
	return &SplunkExporterApplyConfiguration{}
}

// WithEndpoint sets the Endpoint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Endpoint field is set to the value of the last call.
func (b *SplunkExporterApplyConfiguration) WithEndpoint(value string) *SplunkExporterApplyConfiguration {
	b.Endpoint = &value
	return b
}

// WithTokenSecretRef sets the TokenSecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TokenSecretRef field is set to the value of the last call.
func (b *SplunkExporterApplyConfiguration) WithTokenSecretRef(value *SecretKeySelectorApplyConfiguration) *SplunkExporterApplyConfiguration {
	b.TokenSecretRef = value
	return b
}
