/*
Copyright 2026 Ghassan Malke.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ThresholdsApplyConfiguration represents a declarative configuration of the Thresholds type for use
// with apply.
//
// Thresholds control anomaly detection on the agent side.
type ThresholdsApplyConfiguration struct {
	// ErrorRatePercent triggers issue detection when errors exceed this
	// percentage over the rolling window. 0-100.
	ErrorRatePercent *int32 `json:"errorRatePercent,omitempty"`
	// RTTSpikeMs triggers issue detection when network RTT exceeds this
	// value in milliseconds.
	RTTSpikeMs *int32 `json:"rttSpikeMs,omitempty"`
	// FSSlowMs triggers issue detection when a filesystem operation takes
	// longer than this value in milliseconds.
	FSSlowMs *int32 `json:"fsSlowMs,omitempty"`
}

// ThresholdsApplyConfiguration constructs a declarative configuration of the Thresholds type for use with
// apply.
func Thresholds() *ThresholdsApplyConfiguration {
	return &ThresholdsApplyConfiguration{}
}

// WithErrorRatePercent sets the ErrorRatePercent field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ErrorRatePercent field is set to the value of the last call.
func (b *ThresholdsApplyConfiguration) WithErrorRatePercent(value int32) *ThresholdsApplyConfiguration {
	b.ErrorRatePercent = &value
	return b
}

// WithRTTSpikeMs sets the RTTSpikeMs field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RTTSpikeMs field is set to the value of the last call.
func (b *ThresholdsApplyConfiguration) WithRTTSpikeMs(value int32) *ThresholdsApplyConfiguration {
	b.RTTSpikeMs = &value
	return b
}

// WithFSSlowMs sets the FSSlowMs field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FSSlowMs field is set to the value of the last call.
func (b *ThresholdsApplyConfiguration) WithFSSlowMs(value int32) *ThresholdsApplyConfiguration {
	b.FSSlowMs = &value
	return b
}
