/*
Copyright 2026 Ghassan Malke.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// TracerConfigStatusApplyConfiguration represents a declarative configuration of the TracerConfigStatus type for use
// with apply.
//
// TracerConfigStatus reflects the observed state of a TracerConfig.
type TracerConfigStatusApplyConfiguration struct {
	DesiredAgents      *int32                           `json:"desiredAgents,omitempty"`
	ReadyAgents        *int32                           `json:"readyAgents,omitempty"`
	ActiveSessions     *int32                           `json:"activeSessions,omitempty"`
	Conditions         []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	ObservedGeneration *int64                           `json:"observedGeneration,omitempty"`
}

// TracerConfigStatusApplyConfiguration constructs a declarative configuration of the TracerConfigStatus type for use with
// apply.
func TracerConfigStatus() *TracerConfigStatusApplyConfiguration {
	return &TracerConfigStatusApplyConfiguration{}
}

// WithDesiredAgents sets the DesiredAgents field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DesiredAgents field is set to the value of the last call.
func (b *TracerConfigStatusApplyConfiguration) WithDesiredAgents(value int32) *TracerConfigStatusApplyConfiguration {
	b.DesiredAgents = &value
	return b
}

// WithReadyAgents sets the ReadyAgents field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReadyAgents field is set to the value of the last call.
func (b *TracerConfigStatusApplyConfiguration) WithReadyAgents(value int32) *TracerConfigStatusApplyConfiguration {
	b.ReadyAgents = &value
	return b
}

// WithActiveSessions sets the ActiveSessions field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ActiveSessions field is set to the value of the last call.
func (b *TracerConfigStatusApplyConfiguration) WithActiveSessions(value int32) *TracerConfigStatusApplyConfiguration {
	b.ActiveSessions = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *TracerConfigStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *TracerConfigStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *TracerConfigStatusApplyConfiguration) WithObservedGeneration(value int64) *TracerConfigStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}
