/*
Copyright 2026 Ghassan Malke.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/podtrace/podtrace/api/v1alpha1"
	v1 "k8s.io/api/core/v1"
)

// TracerConfigSpecApplyConfiguration represents a declarative configuration of the TracerConfigSpec type for use
// with apply.
//
// TracerConfigSpec configures the tracer infrastructure. It is cluster-scoped
// because it governs a fleet-wide DaemonSet and the Jobs the operator spawns.
type TracerConfigSpecApplyConfiguration struct {
	Image                        *string                               `json:"image,omitempty"`
	ImagePullPolicy              *v1.PullPolicy                        `json:"imagePullPolicy,omitempty"`
	ImagePullSecrets             []v1.LocalObjectReference             `json:"imagePullSecrets,omitempty"`
	Agent                        *AgentSpecApplyConfiguration          `json:"agent,omitempty"`
	Session                      *SessionRuntimeSpecApplyConfiguration `json:"session,omitempty"`
	Redaction                    *RedactionSpecApplyConfiguration      `json:"redaction,omitempty"`
	Capture                      *CaptureSpecApplyConfiguration        `json:"capture,omitempty"`
	NodeSelector                 map[string]string                     `json:"nodeSelector,omitempty"`
	Tolerations                  []v1.Toleration                       `json:"tolerations,omitempty"`
	Affinity                     *v1.Affinity                          `json:"affinity,omitempty"`
	BTFMode                      *apiv1alpha1.BTFMode                  `json:"btfMode,omitempty"`
	MaxConcurrentSessionsPerNode *int32                                `json:"maxConcurrentSessionsPerNode,omitempty"`
	SystemNamespace              *string                               `json:"systemNamespace,omitempty"`
}

// TracerConfigSpecApplyConfiguration constructs a declarative configuration of the TracerConfigSpec type for use with
// apply.
func TracerConfigSpec() *TracerConfigSpecApplyConfiguration {
	return &TracerConfigSpecApplyConfiguration{}
}

// WithImage sets the Image field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Image field is set to the value of the last call.
func (b *TracerConfigSpecApplyConfiguration) WithImage(value string) *TracerConfigSpecApplyConfiguration {
	b.Image = &value
	return b
}

// WithImagePullPolicy sets the ImagePullPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ImagePullPolicy field is set to the value of the last call.
func (b *TracerConfigSpecApplyConfiguration) WithImagePullPolicy(value v1.PullPolicy) *TracerConfigSpecApplyConfiguration {
	b.ImagePullPolicy = &value
	return b
}

// WithImagePullSecrets adds the given value to the ImagePullSecrets field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ImagePullSecrets field.
func (b *TracerConfigSpecApplyConfiguration) WithImagePullSecrets(values ...v1.LocalObjectReference) *TracerConfigSpecApplyConfiguration {
	for i := range values {
		b.ImagePullSecrets = append(b.ImagePullSecrets, values[i])
	}
	return b
}

// WithAgent sets the Agent field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Agent field is set to the value of the last call.
func (b *TracerConfigSpecApplyConfiguration) WithAgent(value *AgentSpecApplyConfiguration) *TracerConfigSpecApplyConfiguration {
	b.Agent = value
	return b
}

// WithSession sets the Session field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Session field is set to the value of the last call.
func (b *TracerConfigSpecApplyConfiguration) WithSession(value *SessionRuntimeSpecApplyConfiguration) *TracerConfigSpecApplyConfiguration {
	b.Session = value
	return b
}

// WithRedaction sets the Redaction field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Redaction field is set to the value of the last call.
func (b *TracerConfigSpecApplyConfiguration) WithRedaction(value *RedactionSpecApplyConfiguration) *TracerConfigSpecApplyConfiguration {
	b.Redaction = value
	return b
}

// WithCapture sets the Capture field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Capture field is set to the value of the last call.
func (b *TracerConfigSpecApplyConfiguration) WithCapture(value *CaptureSpecApplyConfiguration) *TracerConfigSpecApplyConfiguration {
	b.Capture = value
	return b
}

// WithNodeSelector puts the entries into the NodeSelector field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the NodeSelector field,
// overwriting an existing map entries in NodeSelector field with the same key.
func (b *TracerConfigSpecApplyConfiguration) WithNodeSelector(entries map[string]string) *TracerConfigSpecApplyConfiguration {
	if b.NodeSelector == nil && len(entries) > 0 {
		b.NodeSelector = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.NodeSelector[k] = v
	}
	return b
}

// WithTolerations adds the given value to the Tolerations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Tolerations field.
func (b *TracerConfigSpecApplyConfiguration) WithTolerations(values ...v1.Toleration) *TracerConfigSpecApplyConfiguration {
	for i := range values {
		b.Tolerations = append(b.Tolerations, values[i])
	}
	return b
}

// WithAffinity sets the Affinity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Affinity field is set to the value of the last call.
func (b *TracerConfigSpecApplyConfiguration) WithAffinity(value v1.Affinity) *TracerConfigSpecApplyConfiguration {
	b.Affinity = &value
	return b
}

// WithBTFMode sets the BTFMode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BTFMode field is set to the value of the last call.
func (b *TracerConfigSpecApplyConfiguration) WithBTFMode(value apiv1alpha1.BTFMode) *TracerConfigSpecApplyConfiguration {
	b.BTFMode = &value
	return b
}

// WithMaxConcurrentSessionsPerNode sets the MaxConcurrentSessionsPerNode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxConcurrentSessionsPerNode field is set to the value of the last call.
func (b *TracerConfigSpecApplyConfiguration) WithMaxConcurrentSessionsPerNode(value int32) *TracerConfigSpecApplyConfiguration {
	b.MaxConcurrentSessionsPerNode = &value
	return b
}

// WithSystemNamespace sets the SystemNamespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SystemNamespace field is set to the value of the last call.
func (b *TracerConfigSpecApplyConfiguration) WithSystemNamespace(value string) *TracerConfigSpecApplyConfiguration {
	b.SystemNamespace = &value
	return b
}
