/*
Copyright 2026 Ghassan Malke.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/gma1k/podtrace/api/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// TriggerSpecApplyConfiguration represents a declarative configuration of the TriggerSpec type for use
// with apply.
//
// TriggerSpec configures event-driven ("flight recorder") session creation.
type TriggerSpecApplyConfiguration struct {
	// Sources are the alert categories that fire a session. A session fires
	// when an observed alert matches ANY listed source (its Kind and at
	// least its MinSeverity).
	Sources []TriggerSourceApplyConfiguration `json:"sources,omitempty"`
	// Selector narrows which pods' alerts arm the trigger. An empty
	// selector matches every pod in scope (subject to NamespaceSelector).
	Selector *v1.LabelSelectorApplyConfiguration `json:"selector,omitempty"`
	// NamespaceSelector widens matching across namespaces, subject to the
	// same target-namespace consent model as PodTrace.
	NamespaceSelector *v1.LabelSelectorApplyConfiguration `json:"namespaceSelector,omitempty"`
	// Cooldown is the minimum time after a session fires for a given pod
	// before another session may fire for that same pod.
	Cooldown *metav1.Duration `json:"cooldown,omitempty"`
	// MaxSessionsPerHour caps how many triggered sessions this schedule may
	// create per rolling hour across all pods, a fleet-wide backstop against
	// a broad alert storm.
	MaxSessionsPerHour *int32 `json:"maxSessionsPerHour,omitempty"`
	// ConcurrencyPolicy governs overlap with already-active triggered
	// sessions. Defaults to Forbid, the safe default for the privileged
	// Jobs a session runs.
	ConcurrencyPolicy *apiv1alpha1.ConcurrencyPolicy `json:"concurrencyPolicy,omitempty"`
}

// TriggerSpecApplyConfiguration constructs a declarative configuration of the TriggerSpec type for use with
// apply.
func TriggerSpec() *TriggerSpecApplyConfiguration {
	return &TriggerSpecApplyConfiguration{}
}

// WithSources adds the given value to the Sources field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Sources field.
func (b *TriggerSpecApplyConfiguration) WithSources(values ...*TriggerSourceApplyConfiguration) *TriggerSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithSources")
		}
		b.Sources = append(b.Sources, *values[i])
	}
	return b
}

// WithSelector sets the Selector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Selector field is set to the value of the last call.
func (b *TriggerSpecApplyConfiguration) WithSelector(value *v1.LabelSelectorApplyConfiguration) *TriggerSpecApplyConfiguration {
	b.Selector = value
	return b
}

// WithNamespaceSelector sets the NamespaceSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NamespaceSelector field is set to the value of the last call.
func (b *TriggerSpecApplyConfiguration) WithNamespaceSelector(value *v1.LabelSelectorApplyConfiguration) *TriggerSpecApplyConfiguration {
	b.NamespaceSelector = value
	return b
}

// WithCooldown sets the Cooldown field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Cooldown field is set to the value of the last call.
func (b *TriggerSpecApplyConfiguration) WithCooldown(value metav1.Duration) *TriggerSpecApplyConfiguration {
	b.Cooldown = &value
	return b
}

// WithMaxSessionsPerHour sets the MaxSessionsPerHour field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxSessionsPerHour field is set to the value of the last call.
func (b *TriggerSpecApplyConfiguration) WithMaxSessionsPerHour(value int32) *TriggerSpecApplyConfiguration {
	b.MaxSessionsPerHour = &value
	return b
}

// WithConcurrencyPolicy sets the ConcurrencyPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConcurrencyPolicy field is set to the value of the last call.
func (b *TriggerSpecApplyConfiguration) WithConcurrencyPolicy(value apiv1alpha1.ConcurrencyPolicy) *TriggerSpecApplyConfiguration {
	b.ConcurrencyPolicy = &value
	return b
}
