/*
Copyright 2026 Ghassan Malke.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// TriggerStatusApplyConfiguration represents a declarative configuration of the TriggerStatus type for use
// with apply.
//
// TriggerStatus records trigger firing history. Present only for
// trigger-mode schedules.
type TriggerStatusApplyConfiguration struct {
	// RecentFirings is a bounded, time-ordered log (oldest first) of the
	// sessions this trigger created. The controller prunes entries older
	// than the cooldown and the rate window so it cannot grow unbounded.
	RecentFirings []TriggerFiringApplyConfiguration `json:"recentFirings,omitempty"`
}

// TriggerStatusApplyConfiguration constructs a declarative configuration of the TriggerStatus type for use with
// apply.
func TriggerStatus() *TriggerStatusApplyConfiguration {
	return &TriggerStatusApplyConfiguration{}
}

// WithRecentFirings adds the given value to the RecentFirings field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the RecentFirings field.
func (b *TriggerStatusApplyConfiguration) WithRecentFirings(values ...*TriggerFiringApplyConfiguration) *TriggerStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithRecentFirings")
		}
		b.RecentFirings = append(b.RecentFirings, *values[i])
	}
	return b
}
