/*
Copyright 2026 Ghassan Malke.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// TriggerFiringApplyConfiguration represents a declarative configuration of the TriggerFiring type for use
// with apply.
type TriggerFiringApplyConfiguration struct {
	PodName     *string  `json:"podName,omitempty"`
	Namespace   *string  `json:"namespace,omitempty"`
	Time        *v1.Time `json:"time,omitempty"`
	SessionName *string  `json:"sessionName,omitempty"`
}

// TriggerFiringApplyConfiguration constructs a declarative configuration of the TriggerFiring type for use with
// apply.
func TriggerFiring() *TriggerFiringApplyConfiguration {
	return &TriggerFiringApplyConfiguration{}
}

// WithPodName sets the PodName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodName field is set to the value of the last call.
func (b *TriggerFiringApplyConfiguration) WithPodName(value string) *TriggerFiringApplyConfiguration {
	b.PodName = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *TriggerFiringApplyConfiguration) WithNamespace(value string) *TriggerFiringApplyConfiguration {
	b.Namespace = &value
	return b
}

// WithTime sets the Time field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Time field is set to the value of the last call.
func (b *TriggerFiringApplyConfiguration) WithTime(value v1.Time) *TriggerFiringApplyConfiguration {
	b.Time = &value
	return b
}

// WithSessionName sets the SessionName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SessionName field is set to the value of the last call.
func (b *TriggerFiringApplyConfiguration) WithSessionName(value string) *TriggerFiringApplyConfiguration {
	b.SessionName = &value
	return b
}
