/*
Copyright 2026 Ghassan Malke.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/podtrace/podtrace/api/v1alpha1"
)

// TriggerSourceApplyConfiguration represents a declarative configuration of the TriggerSource type for use
// with apply.
//
// TriggerSource selects one alert category and the minimum severity that
// arms the trigger.
type TriggerSourceApplyConfiguration struct {
	Kind *apiv1alpha1.TriggerSourceKind `json:"kind,omitempty"`
	// MinSeverity is the minimum alert severity that fires, ordered
	// warning < critical < fatal. Defaults to critical so noisy warnings
	// do not spawn privileged Jobs unless explicitly opted into.
	MinSeverity *string `json:"minSeverity,omitempty"`
}

// TriggerSourceApplyConfiguration constructs a declarative configuration of the TriggerSource type for use with
// apply.
func TriggerSource() *TriggerSourceApplyConfiguration {
	return &TriggerSourceApplyConfiguration{}
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *TriggerSourceApplyConfiguration) WithKind(value apiv1alpha1.TriggerSourceKind) *TriggerSourceApplyConfiguration {
	b.Kind = &value
	return b
}

// WithMinSeverity sets the MinSeverity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinSeverity field is set to the value of the last call.
func (b *TriggerSourceApplyConfiguration) WithMinSeverity(value string) *TriggerSourceApplyConfiguration {
	b.MinSeverity = &value
	return b
}
