name: Bug Report
description: Create a report to help us improve
title: "bug: "
labels:
  - kind/bug
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: Please provide a clear and concise description of the bug.
      placeholder: |
        Add logs and screenshots if any.
    validations:
      required: true

  - type: textarea
    id: reproducing
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Run 'podtrace -n <namespace> <pod-name> ...'
        2. Execute '...'
        3. Observe the error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behaviour
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - eBPF Programs
        - Event Collection
        - Kubernetes Integration
        - Event Processing
        - Diagnostics
        - Metrics Export
        - CLI
        - Other
    validations:
      required: true

  - type: input
    id: kubernetes_version
    attributes:
      label: Kubernetes version
      description: Output of `kubectl version` (server version)
      placeholder: e.g., v1.28.0
    validations:
      required: false

  - type: input
    id: podtrace_version
    attributes:
      label: podtrace version
      description: Version of podtrace binary
      placeholder: e.g., v0.1.0
    validations:
      required: false

  - type: input
    id: kernel_version
    attributes:
      label: Kernel version
      description: Output of `uname -r` on the node where podtrace runs
      placeholder: e.g., 5.15.0
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (logs, cluster setup, pod configuration, etc.).
