/*
Copyright 2026 Ghassan Malke.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/podtrace/podtrace/pkg/client/clientset/versioned/typed/api/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakePodtraceV1alpha1 struct {
	*testing.Fake
}

func (c *FakePodtraceV1alpha1) ExporterConfigs(namespace string) v1alpha1.ExporterConfigInterface {
	return newFakeExporterConfigs(c, namespace)
}

func (c *FakePodtraceV1alpha1) PodTraces(namespace string) v1alpha1.PodTraceInterface {
	return newFakePodTraces(c, namespace)
}

func (c *FakePodtraceV1alpha1) PodTraceSchedules(namespace string) v1alpha1.PodTraceScheduleInterface {
	return newFakePodTraceSchedules(c, namespace)
}

func (c *FakePodtraceV1alpha1) PodTraceSessions(namespace string) v1alpha1.PodTraceSessionInterface {
	return newFakePodTraceSessions(c, namespace)
}

func (c *FakePodtraceV1alpha1) TracerConfigs() v1alpha1.TracerConfigInterface {
	return newFakeTracerConfigs(c)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakePodtraceV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
