/*
Copyright 2026 Ghassan Malke.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/podtrace/podtrace/api/v1alpha1"
	apiv1alpha1 "github.com/podtrace/podtrace/pkg/client/clientset/versioned/typed/api/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakePodTraceSessions implements PodTraceSessionInterface
type fakePodTraceSessions struct {
	*gentype.FakeClientWithList[*v1alpha1.PodTraceSession, *v1alpha1.PodTraceSessionList]
	Fake *FakePodtraceV1alpha1
}

func newFakePodTraceSessions(fake *FakePodtraceV1alpha1, namespace string) apiv1alpha1.PodTraceSessionInterface {
	return &fakePodTraceSessions{
		gentype.NewFakeClientWithList[*v1alpha1.PodTraceSession, *v1alpha1.PodTraceSessionList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("podtracesessions"),
			v1alpha1.SchemeGroupVersion.WithKind("PodTraceSession"),
			func() *v1alpha1.PodTraceSession { return &v1alpha1.PodTraceSession{} },
			func() *v1alpha1.PodTraceSessionList { return &v1alpha1.PodTraceSessionList{} },
			func(dst, src *v1alpha1.PodTraceSessionList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.PodTraceSessionList) []*v1alpha1.PodTraceSession {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.PodTraceSessionList, items []*v1alpha1.PodTraceSession) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
