/*
Copyright 2026 Ghassan Malke.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	http "net/http"

	apiv1alpha1 "github.com/podtrace/podtrace/api/v1alpha1"
	scheme "github.com/podtrace/podtrace/pkg/client/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type PodtraceV1alpha1Interface interface {
	RESTClient() rest.Interface
	ExporterConfigsGetter
	PodTracesGetter
	PodTraceSessionsGetter
	TracerConfigsGetter
}

// PodtraceV1alpha1Client is used to interact with features provided by the podtrace.io group.
type PodtraceV1alpha1Client struct {
	restClient rest.Interface
}

func (c *PodtraceV1alpha1Client) ExporterConfigs(namespace string) ExporterConfigInterface {
	return newExporterConfigs(c, namespace)
}

func (c *PodtraceV1alpha1Client) PodTraces(namespace string) PodTraceInterface {
	return newPodTraces(c, namespace)
}

func (c *PodtraceV1alpha1Client) PodTraceSessions(namespace string) PodTraceSessionInterface {
	return newPodTraceSessions(c, namespace)
}

func (c *PodtraceV1alpha1Client) TracerConfigs() TracerConfigInterface {
	return newTracerConfigs(c)
}

// NewForConfig creates a new PodtraceV1alpha1Client for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*PodtraceV1alpha1Client, error) {
	config := *c
	setConfigDefaults(&config)
	httpClient, err := rest.HTTPClientFor(&config)
	if err != nil {
		return nil, err
	}
	return NewForConfigAndClient(&config, httpClient)
}

// NewForConfigAndClient creates a new PodtraceV1alpha1Client for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*PodtraceV1alpha1Client, error) {
	config := *c
	setConfigDefaults(&config)
	client, err := rest.RESTClientForConfigAndClient(&config, h)
	if err != nil {
		return nil, err
	}
	return &PodtraceV1alpha1Client{client}, nil
}

// NewForConfigOrDie creates a new PodtraceV1alpha1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *PodtraceV1alpha1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new PodtraceV1alpha1Client for the given RESTClient.
func New(c rest.Interface) *PodtraceV1alpha1Client {
	return &PodtraceV1alpha1Client{c}
}

func setConfigDefaults(config *rest.Config) {
	gv := apiv1alpha1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = rest.CodecFactoryForGeneratedClient(scheme.Scheme, scheme.Codecs).WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *PodtraceV1alpha1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
