/*
Copyright 2026 Ghassan Malke.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	apiv1alpha1 "github.com/podtrace/podtrace/api/v1alpha1"
	applyconfigurationapiv1alpha1 "github.com/podtrace/podtrace/pkg/client/applyconfiguration/api/v1alpha1"
	scheme "github.com/podtrace/podtrace/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ApplicationTracesGetter has a method to return a ApplicationTraceInterface.
// A group's client should implement this interface.
type ApplicationTracesGetter interface {
	ApplicationTraces(namespace string) ApplicationTraceInterface
}

// ApplicationTraceInterface has methods to work with ApplicationTrace resources.
type ApplicationTraceInterface interface {
	Create(ctx context.Context, applicationTrace *apiv1alpha1.ApplicationTrace, opts v1.CreateOptions) (*apiv1alpha1.ApplicationTrace, error)
	Update(ctx context.Context, applicationTrace *apiv1alpha1.ApplicationTrace, opts v1.UpdateOptions) (*apiv1alpha1.ApplicationTrace, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, applicationTrace *apiv1alpha1.ApplicationTrace, opts v1.UpdateOptions) (*apiv1alpha1.ApplicationTrace, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1alpha1.ApplicationTrace, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1alpha1.ApplicationTraceList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1alpha1.ApplicationTrace, err error)
	Apply(ctx context.Context, applicationTrace *applyconfigurationapiv1alpha1.ApplicationTraceApplyConfiguration, opts v1.ApplyOptions) (result *apiv1alpha1.ApplicationTrace, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, applicationTrace *applyconfigurationapiv1alpha1.ApplicationTraceApplyConfiguration, opts v1.ApplyOptions) (result *apiv1alpha1.ApplicationTrace, err error)
	ApplicationTraceExpansion
}

// applicationTraces implements ApplicationTraceInterface
type applicationTraces struct {
	*gentype.ClientWithListAndApply[*apiv1alpha1.ApplicationTrace, *apiv1alpha1.ApplicationTraceList, *applyconfigurationapiv1alpha1.ApplicationTraceApplyConfiguration]
}

// newApplicationTraces returns a ApplicationTraces
func newApplicationTraces(c *PodtraceV1alpha1Client, namespace string) *applicationTraces {
	return &applicationTraces{
		gentype.NewClientWithListAndApply[*apiv1alpha1.ApplicationTrace, *apiv1alpha1.ApplicationTraceList, *applyconfigurationapiv1alpha1.ApplicationTraceApplyConfiguration](
			"applicationtraces",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv1alpha1.ApplicationTrace { return &apiv1alpha1.ApplicationTrace{} },
			func() *apiv1alpha1.ApplicationTraceList { return &apiv1alpha1.ApplicationTraceList{} },
		),
	}
}
