/*
Copyright 2026 Ghassan Malke.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	apiv1alpha1 "github.com/podtrace/podtrace/api/v1alpha1"
	applyconfigurationapiv1alpha1 "github.com/podtrace/podtrace/pkg/client/applyconfiguration/api/v1alpha1"
	scheme "github.com/podtrace/podtrace/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ExporterConfigsGetter has a method to return a ExporterConfigInterface.
// A group's client should implement this interface.
type ExporterConfigsGetter interface {
	ExporterConfigs(namespace string) ExporterConfigInterface
}

// ExporterConfigInterface has methods to work with ExporterConfig resources.
type ExporterConfigInterface interface {
	Create(ctx context.Context, exporterConfig *apiv1alpha1.ExporterConfig, opts v1.CreateOptions) (*apiv1alpha1.ExporterConfig, error)
	Update(ctx context.Context, exporterConfig *apiv1alpha1.ExporterConfig, opts v1.UpdateOptions) (*apiv1alpha1.ExporterConfig, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, exporterConfig *apiv1alpha1.ExporterConfig, opts v1.UpdateOptions) (*apiv1alpha1.ExporterConfig, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1alpha1.ExporterConfig, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1alpha1.ExporterConfigList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1alpha1.ExporterConfig, err error)
	Apply(ctx context.Context, exporterConfig *applyconfigurationapiv1alpha1.ExporterConfigApplyConfiguration, opts v1.ApplyOptions) (result *apiv1alpha1.ExporterConfig, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, exporterConfig *applyconfigurationapiv1alpha1.ExporterConfigApplyConfiguration, opts v1.ApplyOptions) (result *apiv1alpha1.ExporterConfig, err error)
	ExporterConfigExpansion
}

// exporterConfigs implements ExporterConfigInterface
type exporterConfigs struct {
	*gentype.ClientWithListAndApply[*apiv1alpha1.ExporterConfig, *apiv1alpha1.ExporterConfigList, *applyconfigurationapiv1alpha1.ExporterConfigApplyConfiguration]
}

// newExporterConfigs returns a ExporterConfigs
func newExporterConfigs(c *PodtraceV1alpha1Client, namespace string) *exporterConfigs {
	return &exporterConfigs{
		gentype.NewClientWithListAndApply[*apiv1alpha1.ExporterConfig, *apiv1alpha1.ExporterConfigList, *applyconfigurationapiv1alpha1.ExporterConfigApplyConfiguration](
			"exporterconfigs",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv1alpha1.ExporterConfig { return &apiv1alpha1.ExporterConfig{} },
			func() *apiv1alpha1.ExporterConfigList { return &apiv1alpha1.ExporterConfigList{} },
		),
	}
}
