/*
Copyright 2026 Ghassan Malke.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	apiv1alpha1 "github.com/podtrace/podtrace/api/v1alpha1"
	applyconfigurationapiv1alpha1 "github.com/podtrace/podtrace/pkg/client/applyconfiguration/api/v1alpha1"
	scheme "github.com/podtrace/podtrace/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// TracerConfigsGetter has a method to return a TracerConfigInterface.
// A group's client should implement this interface.
type TracerConfigsGetter interface {
	TracerConfigs() TracerConfigInterface
}

// TracerConfigInterface has methods to work with TracerConfig resources.
type TracerConfigInterface interface {
	Create(ctx context.Context, tracerConfig *apiv1alpha1.TracerConfig, opts v1.CreateOptions) (*apiv1alpha1.TracerConfig, error)
	Update(ctx context.Context, tracerConfig *apiv1alpha1.TracerConfig, opts v1.UpdateOptions) (*apiv1alpha1.TracerConfig, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, tracerConfig *apiv1alpha1.TracerConfig, opts v1.UpdateOptions) (*apiv1alpha1.TracerConfig, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1alpha1.TracerConfig, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1alpha1.TracerConfigList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1alpha1.TracerConfig, err error)
	Apply(ctx context.Context, tracerConfig *applyconfigurationapiv1alpha1.TracerConfigApplyConfiguration, opts v1.ApplyOptions) (result *apiv1alpha1.TracerConfig, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, tracerConfig *applyconfigurationapiv1alpha1.TracerConfigApplyConfiguration, opts v1.ApplyOptions) (result *apiv1alpha1.TracerConfig, err error)
	TracerConfigExpansion
}

// tracerConfigs implements TracerConfigInterface
type tracerConfigs struct {
	*gentype.ClientWithListAndApply[*apiv1alpha1.TracerConfig, *apiv1alpha1.TracerConfigList, *applyconfigurationapiv1alpha1.TracerConfigApplyConfiguration]
}

// newTracerConfigs returns a TracerConfigs
func newTracerConfigs(c *PodtraceV1alpha1Client) *tracerConfigs {
	return &tracerConfigs{
		gentype.NewClientWithListAndApply[*apiv1alpha1.TracerConfig, *apiv1alpha1.TracerConfigList, *applyconfigurationapiv1alpha1.TracerConfigApplyConfiguration](
			"tracerconfigs",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *apiv1alpha1.TracerConfig { return &apiv1alpha1.TracerConfig{} },
			func() *apiv1alpha1.TracerConfigList { return &apiv1alpha1.TracerConfigList{} },
		),
	}
}
