#!/bin/bash
#
# wrap-crds.sh — re-apply Helm toggle guards to CRD YAMLs regenerated by
# controller-gen. Called from `make manifests`.
#
#   1. Wrap each CRD YAML in `{{- if .Values.crds.install }} ... {{- end }}`
#      so the user can opt out of CRD installation via values.yaml.
#   2. Inject a conditional `helm.sh/resource-policy: keep` annotation under
#      metadata.annotations so `helm uninstall` does not delete the CRDs
#      (and any CRs depending on them) by default.
#
# Idempotent: safe to run repeatedly.

# Usage:
#   hack/wrap-crds.sh <crd-directory>

set -euo pipefail

readonly SCRIPT_NAME="${0##*/}"

log_err() {
	printf '%s: %s\n' "${SCRIPT_NAME}" "$*" >&2
}

log_info() {
	printf '%s: %s\n' "${SCRIPT_NAME}" "$*"
}

usage() {
	cat >&2 <<USAGE
Usage: ${SCRIPT_NAME} <crd-directory>

Re-applies Helm install/keep toggle guards to CRD YAMLs emitted by
controller-gen. Safe to re-run on an already-wrapped directory.
USAGE
}

main() {
	if [[ $# -ne 1 ]]; then
		usage
		exit 2
	fi

	local crd_dir="$1"
	if [[ ! -d "${crd_dir}" ]]; then
		log_err "not a directory: ${crd_dir}"
		exit 1
	fi

	# nullglob: when no CRD files match, expand to an empty array instead of
	# the literal pattern (avoids iterating over a non-existent filename).
	shopt -s nullglob
	local files=("${crd_dir}"/podtrace.io_*.yaml)
	if [[ ${#files[@]} -eq 0 ]]; then
		log_err "no CRD files found under ${crd_dir}"
		exit 1
	fi

	local file
	for file in "${files[@]}"; do
		wrap_install_toggle "${file}"
		inject_keep_annotation "${file}"
	done

	log_info "processed ${#files[@]} file(s) in ${crd_dir}"
}

# wrap_install_toggle wraps a CRD YAML with the outer Helm install toggle.
# Idempotent: detects the toggle on line 1 and exits early if already present.
wrap_install_toggle() {
	local file="$1"
	local marker='{{- if .Values.crds.install }}'

	# shellcheck disable=SC2016
	# Single-quoted so Go-template braces are preserved literally.
	if head -n1 "${file}" | grep -qF "${marker}"; then
		return 0
	fi

	local tmp
	tmp="$(mktemp)"
	# Clean up tmp on any error before the mv happens.
	trap 'rm -f "${tmp}"' RETURN

	{
		printf '%s\n' "${marker}"
		cat "${file}"
		printf '%s\n' '{{- end }}'
	} >"${tmp}"

	mv "${tmp}" "${file}"
	# mv renamed tmp; clear the trap so RETURN does not try to remove the
	# now-renamed destination.
	trap - RETURN
}

# inject_keep_annotation inserts a conditional `helm.sh/resource-policy: keep`
# annotation into the CRD's metadata.annotations block, directly after the
# controller-gen version marker. Idempotent: skips files that already contain
# the annotation.
#
# Implemented in Python because we need a multiline regex replace with exact
# indentation preservation — sed/awk flavors vary too much across distros.
inject_keep_annotation() {
	local file="$1"
	python3 - "${file}" <<'PY'
import pathlib
import re
import sys

path = pathlib.Path(sys.argv[1])
text = path.read_text()
if "helm.sh/resource-policy" in text:
    sys.exit(0)

match = re.search(
    r"^(\s+)controller-gen\.kubebuilder\.io/version: \S+",
    text,
    re.MULTILINE,
)
if not match:
    sys.exit(f"wrap-crds: controller-gen marker not found in {path}")

indent = match.group(1)
replacement = (
    f"{match.group(0)}\n"
    f"{indent}{{{{- if .Values.crds.keep }}}}\n"
    f"{indent}helm.sh/resource-policy: keep\n"
    f"{indent}{{{{- end }}}}"
)
path.write_text(text.replace(match.group(0), replacement, 1))
PY
}

main "$@"
