// SPDX-License-Identifier: GPL-2.0

#include "common.h"
#include "maps.h"
#include "events.h"
#include "helpers.h"
#include "protocols.h"
#include "resources.c"
#include "network.c"
#include "dns.c"
#include "http3.c"
#include "filesystem.c"
#include "cpu.c"
#include "memory.c"
#include "syscalls.c"
#include "database.c"
#include "redis.c"
#include "memcached.c"
#include "kafka.c"
#include "fastcgi.c"
#include "grpc.c"
#include "http.c"
#include "h2.c"
#include "gotls.c"
#include "grpcgo.c"
#include "rustls.c"
#include "http3l7.c"
#include "crypto.c"

char LICENSE[] SEC("license") = "GPL";
